import type { IconStyleAtom } from "@/lib/atoms/types";

export const ICON_STYLES: readonly IconStyleAtom[] = [
  {
    slug: "outline",
    name: "Outline",
    nameZh: "线性",
    aliases: ["lucide", "feather", "line icon", "线框图标"],
    whenUse: "The default for tool interfaces.",
    whenUseZh: "工具 UI 默认。",
    spec: "Outline icons, 1.5px stroke, round line caps, 24px grid, and even visual weight.",
    specZh: "线性图标，1.5px 描边，圆角端点，24px 网格，视觉重量均匀。",
    rendering: {
      mode: "stroke",
      strokeWidth: 1.5,
      linecap: "round",
      linejoin: "miter",
    },
  },
  {
    slug: "bold-outline",
    name: "Bold Outline",
    nameZh: "粗线",
    aliases: ["2px icon", "2px 图标", "bold line", "粗描边"],
    whenUse: "Lively, youthful interfaces that need more visual weight.",
    whenUseZh: "更活泼年轻、需要更强视觉重量的界面。",
    spec: "Bold outline icons, 2px stroke, round line caps, 24px grid, with lively and even visual weight.",
    specZh: "粗线图标，2px 描边，圆角端点，24px 网格，视觉重量活泼且均匀。",
    rendering: {
      mode: "stroke",
      strokeWidth: 2,
      linecap: "round",
      linejoin: "miter",
    },
  },
  {
    slug: "rounded",
    name: "Rounded",
    nameZh: "圆角线性",
    aliases: ["soft outline", "柔和线性", "consumer icon", "消费级图标"],
    whenUse: "Friendly, consumer-facing products.",
    whenUseZh: "亲和、消费级产品。",
    spec: "Rounded outline icons with clearly rounded caps and joins, a 24px grid, and friendly even weight.",
    specZh: "圆角线性图标，端点与转角明显圆润，24px 网格，视觉重量亲和且均匀。",
    rendering: {
      mode: "stroke",
      strokeWidth: 1.5,
      linecap: "round",
      linejoin: "round",
    },
  },
  {
    slug: "filled",
    name: "Filled",
    nameZh: "面性",
    aliases: ["solid icon", "实心图标", "tab icon", "导航栏图标"],
    whenUse: "High-recognition states such as mobile tab bars.",
    whenUseZh: "高识别度场景，例如移动端 tab 栏。",
    spec: "Filled icons with solid silhouettes, a 24px grid, high recognition, and consistent optical area.",
    specZh: "面性图标，实心轮廓，24px 网格，高识别度，光学占位一致。",
    rendering: { mode: "fill" },
  },
  {
    slug: "duotone",
    name: "Duotone",
    nameZh: "双色调",
    aliases: ["two tone", "双色", "brand icon", "品牌图标"],
    whenUse: "Brand-forward interfaces that can support a stronger icon voice.",
    whenUseZh: "品牌感较强、允许图标更有存在感的界面。",
    spec: "Duotone icons with a solid primary shape and a same-color secondary shape at 30% opacity on a 24px grid.",
    specZh: "双色调图标，主形实色，副形使用同色 30% 透明度，24px 网格。",
    rendering: { mode: "duotone", secondaryOpacity: 0.3 },
  },
  {
    slug: "pixel",
    name: "Pixel",
    nameZh: "像素",
    aliases: ["pixel art", "像素画", "retro computing", "复古计算"],
    whenUse: "Retro-computing aesthetics and deliberately game-like products.",
    whenUseZh: "复古计算美学与刻意游戏化的产品。",
    spec: "Pixel icons built from hard-edged square cells on a 16px grid, with no curves or antialiased diagonals.",
    specZh: "像素图标，16px 方格硬边，以矩形拼合，不使用曲线或抗锯齿斜线。",
    rendering: { mode: "pixel", grid: 16 },
  },
] as const;
