import type { LayerAtom, RadiusAtom, ShadowAtom } from "@/lib/atoms/types";

export const RADII: readonly RadiusAtom[] = [
  {
    slug: "none",
    name: "None",
    nameZh: "无圆角",
    aliases: ["square", "hard edge", "硬边", "直角"],
    whenUse: "Retro terminals and hard-edged Swiss layouts.",
    whenUseZh: "复古终端与瑞士硬边。",
    value: "0",
  },
  {
    slug: "xs",
    name: "Extra Small",
    nameZh: "极小",
    aliases: ["badge radius", "徽章圆角", "mini chip"],
    whenUse: "Badges and miniature chips.",
    whenUseZh: "徽章与迷你 chip。",
    value: "4px",
  },
  {
    slug: "sm",
    name: "Small",
    nameZh: "小",
    aliases: ["control radius", "控件圆角", "inline code"],
    whenUse: "Inline code and small controls.",
    whenUseZh: "行内代码与小控件。",
    value: "6px",
  },
  {
    slug: "md",
    name: "Medium",
    nameZh: "中",
    aliases: ["button radius", "按钮圆角", "row hover"],
    whenUse: "Buttons and row-hover backgrounds.",
    whenUseZh: "按钮与行 hover 底。",
    value: "10px",
  },
  {
    slug: "lg",
    name: "Large",
    nameZh: "大",
    aliases: ["card radius", "卡片圆角", "squircle correction", "超椭圆校正"],
    whenUse: "The default radius for cards.",
    whenUseZh: "卡片默认圆角。",
    value: "12.5px",
    note: "A 1.25× optical correction commonly used to approximate a squircle in tool UIs.",
    noteZh: "工具 UI 惯用 squircle 视觉 ×1.25 校正的产物。",
  },
  {
    slug: "xl",
    name: "Extra Large",
    nameZh: "超大",
    aliases: ["panel radius", "面板圆角", "group card"],
    whenUse: "Panels and grouped cards.",
    whenUseZh: "面板与分组卡。",
    value: "20px",
  },
  {
    slug: "2xl",
    name: "Double Extra Large",
    nameZh: "特大",
    aliases: ["composer radius", "输入台圆角", "large container"],
    whenUse: "Composers and large containers.",
    whenUseZh: "输入台与大容器。",
    value: "25px",
  },
  {
    slug: "full",
    name: "Full",
    nameZh: "全圆",
    aliases: ["pill", "胶囊", "round button", "圆钮"],
    whenUse: "Pills and circular buttons.",
    whenUseZh: "胶囊与圆钮。",
    value: "9999px",
  },
] as const;

export const SHADOWS: readonly ShadowAtom[] = [
  {
    slug: "hairline",
    name: "Hairline",
    nameZh: "发丝",
    aliases: ["shadow border", "阴影描边", "surface line", "贴面线"],
    whenUse: "Flush hierarchy; the first choice when a border would feel too heavy.",
    whenUseZh: "贴面层级，代替边框的首选。",
    light: "0 0 0 0.5px rgb(0 0 0 / 0.08)",
    dark: "0 0 0 0.5px rgb(255 255 255 / 0.157)",
  },
  {
    slug: "raised",
    name: "Raised",
    nameZh: "浮起",
    aliases: ["card shadow", "卡片阴影", "low elevation", "低高度"],
    whenUse: "Cards resting just above the page.",
    whenUseZh: "卡片。",
    light: "0 0 0 0.5px rgb(0 0 0 / 0.06), 0 1px 2px rgb(0 0 0 / 0.05)",
    dark: "0 0 0 0.5px rgb(255 255 255 / 0.1), 0 1px 2px rgb(0 0 0 / 0.4)",
  },
  {
    slug: "floating",
    name: "Floating",
    nameZh: "悬浮",
    aliases: ["popover shadow", "弹层阴影", "compound shadow", "组合影"],
    whenUse: "A compound shadow for popovers and floating panels.",
    whenUseZh: "弹层与 popover 的组合影。",
    light: "0 0 0 0.5px rgb(0 0 0 / 0.08), 0 3px 7.5px rgb(0 0 0 / 0.04), 0 0 20px rgb(0 0 0 / 0.05)",
    dark: "0 0 0 0.5px rgb(255 255 255 / 0.157), 0 3px 7.5px rgb(0 0 0 / 0.2), 0 0 20px rgb(0 0 0 / 0.25)",
  },
  {
    slug: "prominent",
    name: "Prominent",
    nameZh: "显著",
    aliases: ["modal shadow", "模态阴影", "HUD shadow", "HUD 阴影"],
    whenUse: "Modals and persistent HUD cards.",
    whenUseZh: "模态与常驻 HUD 卡。",
    light: "0 0 0 0.5px rgb(0 0 0 / 0.08), 0 12px 32px rgb(0 0 0 / 0.12)",
    dark: "0 0 0 0.5px rgb(255 255 255 / 0.157), 0 12px 32px rgb(0 0 0 / 0.5)",
  },
] as const;

export const LAYERS: readonly LayerAtom[] = [
  {
    slug: "base",
    name: "Base",
    nameZh: "基础",
    aliases: ["page layer", "页面层", "normal flow", "常规流"],
    whenUse: "Regular page content in the normal flow.",
    whenUseZh: "页面常规内容流。",
    z: 0,
  },
  {
    // "lifted", not "raised" — the shadow scale above already owns that slug,
    // and slugs must be unique within a category (they key the search index).
    slug: "lifted",
    name: "Lifted",
    nameZh: "抬升",
    aliases: ["hover lift", "悬浮抬升", "local raise", "局部浮起"],
    whenUse: "A card or element lifted on hover, or raised locally above its siblings.",
    whenUseZh: "hover 抬升的卡片、局部浮起的元素。",
    z: 10,
  },
  {
    slug: "sticky",
    name: "Sticky",
    nameZh: "吸顶",
    aliases: ["sticky nav", "吸顶导航", "toolbar", "工具条"],
    whenUse: "A sticky nav bar or toolbar pinned above scrolling content.",
    whenUseZh: "吸顶导航、工具条。",
    z: 20,
  },
  {
    slug: "dropdown",
    name: "Dropdown",
    nameZh: "下拉层",
    aliases: ["select menu", "下拉菜单", "combobox", "组合框"],
    whenUse: "Dropdown menus, selects, and comboboxes.",
    whenUseZh: "下拉菜单、select、combobox。",
    z: 30,
  },
  {
    slug: "overlay",
    name: "Overlay",
    nameZh: "遮罩层",
    aliases: ["modal layer", "弹层", "drawer", "抽屉"],
    whenUse: "The scrim and panel of a modal or drawer.",
    whenUseZh: "modal、drawer 的遮罩与面板。",
    z: 40,
  },
  {
    slug: "toast",
    name: "Toast",
    nameZh: "提示层",
    aliases: ["toast notification", "toast 通知", "snackbar", "消息条"],
    whenUse: "Toast notifications, which must sit above any open modal.",
    whenUseZh: "toast 通知，需盖过 modal。",
    z: 50,
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    nameZh: "提示气泡",
    aliases: ["tooltip layer", "提示气泡层", "topmost", "最上层"],
    whenUse: "Tooltips, which always render above everything else.",
    whenUseZh: "tooltip，永远最上层。",
    z: 60,
  },
] as const;
