import type { FontPairAtom, TypeScaleAtom } from "@/lib/atoms/types";

const ZERO_LOAD_NOTE = "Chinese always falls back to the system family, with zero font-loading cost.";
const ZERO_LOAD_NOTE_ZH = "中文一律回退系统族，零加载成本。";

export const FONT_PAIRS: readonly FontPairAtom[] = [
  {
    slug: "system-neutral",
    name: "System Neutral",
    nameZh: "系统中性",
    aliases: ["Geist", "Inter", "tool default", "工具默认"],
    whenUse: "The safe default for tool products.",
    whenUseZh: "工具产品默认，不出错的起点。",
    display: "Geist, Inter, system-ui, sans-serif",
    body: "Geist, Inter, system-ui, sans-serif",
    mono: "'Geist Mono', ui-monospace, monospace",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
  },
  {
    slug: "native-crisp",
    name: "Native Crisp",
    nameZh: "原生利落",
    aliases: ["SF Pro", "Apple native", "苹果原生", "desktop app"],
    whenUse: "Desktop-app character that follows the host platform.",
    whenUseZh: "桌面应用感，跟随平台。",
    display: "'SF Pro Display', -apple-system, system-ui",
    body: "'SF Pro Text', -apple-system, system-ui",
    mono: "'SF Mono', ui-monospace, Menlo",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
  },
  {
    slug: "editorial-serif",
    name: "Editorial Serif",
    nameZh: "编辑衬线",
    aliases: ["Tiempos", "editorial", "编辑感", "serif headline", "衬线标题"],
    whenUse: "Content and reading products where the headline sets the tone.",
    whenUseZh: "内容与阅读产品，标题定调。",
    display: "'Tiempos Headline', Georgia, serif",
    body: "-apple-system, 'Segoe UI', sans-serif",
    mono: "ui-monospace, monospace",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
  },
  {
    slug: "humanist-warm",
    name: "Humanist Warm",
    nameZh: "人文暖感",
    aliases: ["Camera Plain", "humanist", "人文", "warm", "暖感"],
    whenUse: "Friendly, handmade, and educational experiences.",
    whenUseZh: "亲和、手作、教育感。",
    display: "'Camera Plain', 'PingFang SC', ui-sans-serif, system-ui",
    body: "'Camera Plain', 'PingFang SC', ui-sans-serif, system-ui",
    mono: "ui-monospace, monospace",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
  },
  {
    slug: "geek-mono",
    name: "Geek Mono",
    nameZh: "极客等宽",
    aliases: ["JetBrains Mono", "terminal", "终端风", "developer toy", "开发者玩具"],
    whenUse: "Terminal aesthetics, developer toys, and retro computing.",
    whenUseZh: "终端风、开发者玩具、复古计算。",
    display: "'JetBrains Mono', 'SF Mono', ui-monospace, monospace",
    body: "ui-sans-serif, system-ui",
    mono: "'JetBrains Mono', 'SF Mono', ui-monospace, monospace",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
  },
  {
    slug: "swiss-grotesk",
    name: "Swiss Grotesk",
    nameZh: "瑞士怪诞",
    aliases: ["Helvetica Neue", "Swiss", "瑞士", "poster typography", "海报排版"],
    whenUse: "Poster-like pages driven by oversized typography.",
    whenUseZh: "海报感、大标题排版驱动的页面。",
    display: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    body: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    mono: "ui-monospace",
    note: ZERO_LOAD_NOTE,
    noteZh: ZERO_LOAD_NOTE_ZH,
    displayNote: "Use heavy display type with negative tracking.",
    displayNoteZh: "大字重 + 负字距。",
  },
] as const;

export const TYPE_SCALE: readonly TypeScaleAtom[] = [
  {
    slug: "display",
    name: "Display",
    nameZh: "展示",
    aliases: ["hero type", "首屏大字"],
    whenUse: "One dominant display line.",
    whenUseZh: "单行主视觉大标题。",
    fontSize: "48px",
    lineHeight: 1.1,
    letterSpacing: "-0.02em",
  },
  {
    slug: "headline",
    name: "Headline",
    nameZh: "头条",
    aliases: ["section heading", "区块标题"],
    whenUse: "Page and section headlines.",
    whenUseZh: "页面与区块主标题。",
    fontSize: "28px",
    lineHeight: 1.2,
    letterSpacing: "-0.01em",
  },
  {
    slug: "title",
    name: "Title",
    nameZh: "标题",
    aliases: ["card title", "卡片标题"],
    whenUse: "Card and panel titles.",
    whenUseZh: "卡片与面板标题。",
    fontSize: "20px",
    lineHeight: 1.3,
    letterSpacing: "0",
  },
  {
    slug: "body",
    name: "Body",
    nameZh: "正文",
    aliases: ["base text", "基础正文"],
    whenUse: "Default reading text.",
    whenUseZh: "默认阅读正文。",
    fontSize: "16px",
    lineHeight: 1.5,
    letterSpacing: "0",
  },
  {
    slug: "body-sm",
    name: "Small Body",
    nameZh: "小正文",
    aliases: ["compact body", "紧凑正文"],
    whenUse: "Compact supporting copy.",
    whenUseZh: "紧凑的辅助正文。",
    fontSize: "14px",
    lineHeight: 1.5,
    letterSpacing: "0",
  },
  {
    slug: "caption",
    name: "Caption",
    nameZh: "说明",
    aliases: ["microcopy", "微文案", "label", "标签字"],
    whenUse: "Labels and explanatory microcopy; loosen the tracking at this size.",
    whenUseZh: "标签与说明小字；小字需放宽字距。",
    fontSize: "12px",
    lineHeight: 1.4,
    letterSpacing: "0.01em",
  },
] as const;

export function fontPairCssValue(pair: FontPairAtom): string {
  return `--font-display: ${pair.display};\n--font-sans: ${pair.body};\n--font-mono: ${pair.mono};`;
}

export function typeScaleCssValue(step: TypeScaleAtom): string {
  return `font-size: ${step.fontSize};\nline-height: ${step.lineHeight};\nletter-spacing: ${step.letterSpacing};`;
}
