import type { StyleEntry } from "./types";

// 材质质感谱系:风格的核心识别点在表面材质(玻璃/软塑料/黏土)。

export const materialStyles: StyleEntry[] = [
  {
    slug: "glassmorphism",
    name: "Glassmorphism",
    nameZh: "玻璃拟态",
    group: "material",
    aliases: ["毛玻璃", "磨砂玻璃", "Frosted Glass", "Glass UI"],
    description:
      "Frosted translucent cards floating over colorful glows, like a pane of misted glass.",
    descriptionZh: "半透明磨砂卡片浮在彩色光斑之上,像一层结了霜的玻璃。",
    bestFor: "Tech product sites, SaaS dashboards, dark-mode music and creative apps",
    bestForZh: "科技产品官网、SaaS 仪表盘、音乐与创意类应用的深色界面",
    promptZh:
      "请用玻璃拟态(Glassmorphism)风格设计这个页面:深色蓝紫渐变背景,上面放 2-3 个大的彩色模糊光斑(青色、紫色);卡片和面板用半透明白色(8%-12% 不透明度)加 backdrop-filter: blur(12px) 磨砂效果,配 1px 半透明白色描边(15%-20%)和 16-24px 的大圆角;文字用白色,次要信息靠降低不透明度区分层级;主按钮用近实色的白底深色字,次按钮保持玻璃质感。禁止:纯白或浅色背景、完全不透明的卡片、生硬的深色阴影、小圆角、给所有元素都加模糊(模糊只属于卡片和导航)。",
    promptEn:
      "Design this page in a glassmorphism style: a dark blue-violet gradient background with 2-3 large blurred color glows (cyan, violet). Cards and panels are translucent white (8-12% opacity) with backdrop-filter: blur(12px), a 1px semi-transparent white border (15-20%) and large 16-24px rounded corners. Text is white; create hierarchy by lowering opacity, not by changing hue. The primary button is near-solid white with dark text; secondary buttons stay glassy. Forbidden: white or light backgrounds, fully opaque cards, harsh dark shadows, small border radii, and blurring everything — blur belongs to cards and the nav only.",
    recipeZh: [
      "backdrop-filter: blur(12px) + 半透明白底 rgba(255,255,255,.08)",
      "1px 半透明白描边 rgba(255,255,255,.16),做出玻璃边缘",
      "深色渐变背景 + 大尺寸彩色模糊光斑(blur 60px 以上)",
      "层级用不透明度表达:主文字 100%,次要 65%",
      "圆角 16-24px,阴影用大而软的环境阴影",
    ],
    recipe: [
      "backdrop-filter: blur(12px) over translucent white rgba(255,255,255,.08)",
      "1px semi-transparent white border rgba(255,255,255,.16) for the glass edge",
      "Dark gradient background + oversized blurred color glows (blur 60px+)",
      "Hierarchy through opacity: primary text 100%, secondary 65%",
      "16-24px radii; shadows stay large, soft and ambient",
    ],
    skin: {
      backdrop: "aurora",
      vars: {
        "--st-page-bg": "linear-gradient(135deg, #10122b 0%, #1b1240 45%, #0c1b33 100%)",
        "--st-page-fg": "#f8fafc",
        "--st-muted": "rgba(248, 250, 252, 0.65)",
        "--st-card-bg": "rgba(255, 255, 255, 0.08)",
        "--st-card-border": "1px solid rgba(255, 255, 255, 0.16)",
        "--st-card-blur": "blur(12px)",
        "--st-radius-lg": "20px",
        "--st-radius-sm": "12px",
        "--st-shadow": "0 8px 32px rgba(2, 6, 23, 0.35)",
        "--st-divider": "1px solid rgba(255, 255, 255, 0.14)",
        "--st-accent": "#67e8f9",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.02em",
        "--st-badge-bg": "rgba(103, 232, 249, 0.14)",
        "--st-badge-fg": "#a5f3fc",
        "--st-badge-border": "1px solid rgba(103, 232, 249, 0.3)",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "rgba(255, 255, 255, 0.92)",
        "--st-btn-primary-fg": "#0f172a",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "0 4px 16px rgba(2, 6, 23, 0.3)",
        "--st-btn-secondary-bg": "rgba(255, 255, 255, 0.08)",
        "--st-btn-secondary-fg": "#f8fafc",
        "--st-btn-secondary-border": "1px solid rgba(255, 255, 255, 0.22)",
      },
    },
  },
  {
    slug: "neumorphism",
    name: "Neumorphism",
    nameZh: "新拟态",
    group: "material",
    aliases: ["软 UI", "Soft UI", "Neomorphism", "单色拟物"],
    description:
      "A single soft gray-blue surface where every card and button seems pressed or embossed by light and shadow alone, no outlines anywhere.",
    descriptionZh: "整站一块柔灰蓝底色,卡片按钮全靠光影凹凸感区分层次,不见一根描边。",
    bestFor: "Wellness and meditation apps, minimalist portfolio sites, calm settings/control panels",
    bestForZh: "冥想 / 健康类 App、极简作品集、需要「安静感」的设置面板",
    promptZh:
      "请用新拟态(Neumorphism)风格设计这个页面:整站单色浅灰蓝背景 #e0e5ec;卡片与背景同色,不用描边,靠双向柔阴影(阳光从左上照射,box-shadow: 9px 9px 16px rgba(163,177,198,.55), -9px -9px 16px rgba(255,255,255,.95))撑出凸起体积感;圆角大而柔和(18px/14px);正文用低对比的靛灰色 #44476a,次要文字 #7b7f9e;强调色是柔和靛蓝 #6c7ee1,只用在主按钮和图标上;主按钮 accent 底、白字,配同款柔阴影;次按钮与背景同色,靠阴影「凸」出来,不加描边;分割线用极淡的 1px #cdd3e0。禁止:纯黑或纯白、任何清晰描边、强对比配色、锐利硬阴影、鲜艳撞色、平面无阴影的卡片。",
    promptEn:
      "Design this page in a neumorphism style: a single-hue light blue-gray background #e0e5ec; cards share the exact same color with no border, relying on a two-directional soft shadow (light from the top-left, box-shadow: 9px 9px 16px rgba(163,177,198,.55), -9px -9px 16px rgba(255,255,255,.95)) to read as embossed volume; corners are large and soft (18px/14px); body text is a low-contrast indigo-gray #44476a, muted text #7b7f9e; the accent is a soft periwinkle #6c7ee1, reserved for the primary button and icons; the primary button sits on the accent color with white text and the same soft shadow; the secondary button matches the page background and only 'pops' via shadow, never a border; dividers are a faint 1px #cdd3e0. Forbidden: pure black or white, any crisp outline, high-contrast color pairs, sharp hard-edged shadows, saturated clashing colors, and flat shadowless cards.",
    recipeZh: [
      "卡片与页面背景同色 #e0e5ec,靠双向柔阴影撑出凸起体积,不加描边",
      "box-shadow: 9px 9px 16px rgba(163,177,198,.55), -9px -9px 16px rgba(255,255,255,.95)",
      "圆角偏大:radius-lg 18px / radius-sm 14px,边缘柔和不生硬",
      "配色收窄在单一色相:靛灰文字 #44476a + 柔靛蓝 accent #6c7ee1",
      "次按钮与底色一致,仅靠阴影方向反转表达按下/凸起状态",
    ],
    recipe: [
      "Cards match the page background #e0e5ec exactly; volume comes from a two-directional soft shadow, never a border",
      "box-shadow: 9px 9px 16px rgba(163,177,198,.55), -9px -9px 16px rgba(255,255,255,.95)",
      "Generous corners: radius-lg 18px / radius-sm 14px for a soft, non-sharp edge",
      "Keep the palette to one hue family: indigo-gray text #44476a plus soft periwinkle accent #6c7ee1",
      "Secondary buttons share the base color; only an inverted shadow direction signals pressed vs. raised",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#e0e5ec",
        "--st-page-fg": "#44476a",
        "--st-muted": "#7b7f9e",
        "--st-card-bg": "#e0e5ec",
        "--st-card-border": "none",
        "--st-card-blur": "none",
        "--st-radius-lg": "18px",
        "--st-radius-sm": "14px",
        "--st-shadow": "9px 9px 16px rgba(163,177,198,.55), -9px -9px 16px rgba(255,255,255,.95)",
        "--st-divider": "1px solid #cdd3e0",
        "--st-accent": "#6c7ee1",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#e6ebf3",
        "--st-badge-fg": "#565a8a",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#6c7ee1",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow":
          "6px 6px 12px rgba(108,126,225,.35), -4px -4px 10px rgba(255,255,255,.6)",
        "--st-btn-secondary-bg": "#e0e5ec",
        "--st-btn-secondary-fg": "#44476a",
        "--st-btn-secondary-border": "none",
      },
    },
  },
  {
    slug: "claymorphism",
    name: "Claymorphism",
    nameZh: "黏土拟态",
    group: "material",
    aliases: ["黏土风", "Clay UI", "3D 软泥风", "Claymorphic"],
    description:
      "Cards look pinched out of soft purple clay, plump and rounded with a light gleam caught in every fold.",
    descriptionZh: "卡片像被捏出来的一坨紫色软泥,浑圆饱满,每一道折痕都留着一点高光。",
    bestFor: "Kids/edu products, mobile game landing pages, playful consumer app onboarding",
    bestForZh: "儿童 / 教育类产品、手游落地页、活泼调性的消费级 App 引导页",
    promptZh:
      "请用黏土拟态(Claymorphism)风格设计这个页面:背景是浅紫雾蓝 #eef1ff;卡片纯白 #ffffff,圆角超大近乎软糖块(30px,小组件 18px);标志性的内外双阴影同时使用——内凹提亮 inset 4px 4px 10px rgba(120,120,190,.18)、内凹高光 inset -6px -6px 12px #ffffff,外层再叠一层向下投影 10px 14px 24px rgba(120,120,190,.28),做出「捏出来的软泥块」体积感;强调色用糖果紫 #7c6cf6;徽章用柔粉底 #ffd6ea 配深紫字;主按钮紫底白字、胶囊感圆角;正文深灰紫 #2f2a45,次要文字 #6f6a8a;标题字重 700,略粗但不生硬。禁止:硬直角、纯黑投影、细描边线框、低饱和灰调、扁平无阴影卡片、玻璃通透感。",
    promptEn:
      "Design this page in a claymorphism style: a soft lavender-blue background #eef1ff; cards are solid white #ffffff with oversized, almost gumdrop-like corners (30px, 18px on small components); the signature move is layering an inset highlight and an outer drop shadow together — inset 4px 4px 10px rgba(120,120,190,.18), inset -6px -6px 12px #ffffff, plus an outer 10px 14px 24px rgba(120,120,190,.28) — so cards read as pinched, puffy clay; the accent is candy purple #7c6cf6; badges sit on soft pink #ffd6ea with deep purple text; the primary button is purple with white text in a pill-like rounded shape; body text is deep grayish purple #2f2a45, muted text #6f6a8a; headings are weight 700, noticeably bold but never harsh. Forbidden: sharp square corners, pure black shadows, thin outline borders, desaturated gray tones, flat shadowless cards, and any glassy transparency.",
    recipeZh: [
      "卡片用内外双阴影叠加:inset 4px 4px 10px rgba(120,120,190,.18) + inset -6px -6px 12px #ffffff + 外层 10px 14px 24px rgba(120,120,190,.28)",
      "圆角拉满:radius-lg 30px / radius-sm 18px,越圆越「软」",
      "纯白卡片配浅紫雾底色 #eef1ff,靠阴影而非描边分层",
      "强调色糖果紫 #7c6cf6 + 徽章柔粉 #ffd6ea,撞色但饱和度克制",
      "标题字重 700 打底,配合大圆角营造饱满的黏土手感",
    ],
    recipe: [
      "Layer inset + outer shadows on the card: inset 4px 4px 10px rgba(120,120,190,.18) + inset -6px -6px 12px #ffffff + an outer 10px 14px 24px rgba(120,120,190,.28)",
      "Push corners to the max: radius-lg 30px / radius-sm 18px — rounder reads softer",
      "Pure white cards over a hazy lavender base #eef1ff; separate layers with shadow, not borders",
      "Candy purple accent #7c6cf6 paired with soft pink badges #ffd6ea — a contained, not garish, clash",
      "Heading weight 700 plus generous radii to keep the puffy clay feel",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#eef1ff",
        "--st-page-fg": "#2f2a45",
        "--st-muted": "#6f6a8a",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "none",
        "--st-card-blur": "none",
        "--st-radius-lg": "30px",
        "--st-radius-sm": "18px",
        "--st-shadow":
          "inset 4px 4px 10px rgba(120,120,190,.18), inset -6px -6px 12px #ffffff, 10px 14px 24px rgba(120,120,190,.28)",
        "--st-divider": "1px solid rgba(120,120,190,.18)",
        "--st-accent": "#7c6cf6",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#ffd6ea",
        "--st-badge-fg": "#6a3fb5",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#7c6cf6",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow":
          "6px 8px 16px rgba(124,108,246,.4), inset -2px -2px 6px rgba(255,255,255,.3)",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#7c6cf6",
        "--st-btn-secondary-border": "1px solid rgba(124,108,246,.25)",
      },
    },
  },
  {
    slug: "liquid-glass",
    name: "Liquid Glass",
    nameZh: "液态玻璃",
    group: "material",
    aliases: ["Liquid Glass", "Apple 液态玻璃", "iOS 26 风格", "水润玻璃"],
    description:
      "Bright, dewy glass panels that glow with saturated light instead of hiding in a dark aurora — Apple's newest surface language.",
    descriptionZh: "明亮水润的玻璃面板,不靠深色极光遮掩,而是让饱和的光透出来——苹果最新的界面语言。",
    bestFor: "Apple ecosystem product pages, iOS app marketing sites, premium consumer hardware launches",
    bestForZh: "苹果生态产品页、iOS App 营销官网、高端消费硬件发布页",
    promptZh:
      "请用液态玻璃(Liquid Glass)风格设计这个页面:背景是浅蓝白渐变 linear-gradient(160deg, #dfe9f5 0%, #f4f8fd 55%, #e3ecf7 100%),明亮通透,不用深色;卡片用半透明白 rgba(255,255,255,.45)叠加 backdrop-filter: blur(20px) saturate(160%),让底色透出饱和度更高的「湿润」质感;描边用近乎实白的 1px solid rgba(255,255,255,.75),在边缘制造一圈液态高光;圆角要么大且圆润(28px),要么直接做成 999px 全胶囊;强调色是纯正的 iOS 蓝 #0a84ff,只用在主按钮和交互态上;正文深灰黑 #1d1d1f,次要文字用同色降到 60% 不透明度;主按钮蓝底白字胶囊形,搭配柔和投影和顶部一条高光线模拟水面反光。禁止:深色背景、低饱和灰蒙蒙的玻璃、生硬直角、无光泽的纯色描边、和玻璃拟态一样的暗色霓虹光斑。",
    promptEn:
      "Design this page in a liquid glass style: a bright blue-white gradient background linear-gradient(160deg, #dfe9f5 0%, #f4f8fd 55%, #e3ecf7 100%) — luminous and airy, never dark; cards are translucent white rgba(255,255,255,.45) layered with backdrop-filter: blur(20px) saturate(160%) so the base color shows through with a wetter, more saturated glow; borders are a near-solid 1px solid rgba(255,255,255,.75) that rings the edge with a liquid highlight; corners are either large and rounded (28px) or pushed all the way to a 999px capsule; the accent is true iOS blue #0a84ff, reserved for the primary button and interactive states; body text is deep near-black #1d1d1f, muted text is the same color at 60% opacity; the primary button is blue with white text in a capsule shape, with a soft shadow and a thin top highlight line to mimic light reflecting off water. Forbidden: dark backgrounds, dull low-saturation glass, hard square corners, matte flat-color borders, and the dark neon color-glow look of classic glassmorphism.",
    recipeZh: [
      "浅蓝白渐变底:linear-gradient(160deg, #dfe9f5 0%, #f4f8fd 55%, #e3ecf7 100%)",
      "卡片 rgba(255,255,255,.45) + backdrop-filter: blur(20px) saturate(160%),饱和度拉高制造「湿润」感",
      "近实白描边 1px solid rgba(255,255,255,.75),边缘留一圈液态高光",
      "圆角要么 28px 大圆,要么 999px 全胶囊,拒绝直角",
      "强调色收窄为单一 iOS 蓝 #0a84ff,配柔和投影 + 顶部高光线模拟水面反光",
    ],
    recipe: [
      "Bright blue-white gradient base: linear-gradient(160deg, #dfe9f5 0%, #f4f8fd 55%, #e3ecf7 100%)",
      "Cards: rgba(255,255,255,.45) + backdrop-filter: blur(20px) saturate(160%) — the saturation boost is what reads as 'wet'",
      "Near-solid white border 1px solid rgba(255,255,255,.75) rings the edge with a liquid highlight",
      "Corners are either a big 28px round or a full 999px capsule — never square",
      "Keep the accent to a single true iOS blue #0a84ff, paired with a soft shadow and a top highlight line for a water-reflection feel",
    ],
    skin: {
      backdrop: "aurora",
      vars: {
        "--st-page-bg": "linear-gradient(160deg, #dfe9f5 0%, #f4f8fd 55%, #e3ecf7 100%)",
        "--st-page-fg": "#1d1d1f",
        "--st-muted": "rgba(29, 29, 31, 0.6)",
        "--st-card-bg": "rgba(255, 255, 255, 0.45)",
        "--st-card-border": "1px solid rgba(255, 255, 255, 0.75)",
        "--st-card-blur": "blur(20px) saturate(160%)",
        "--st-radius-lg": "28px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 8px 32px rgba(31, 68, 122, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.6)",
        "--st-divider": "1px solid rgba(29, 29, 31, 0.08)",
        "--st-accent": "#0a84ff",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "rgba(10, 132, 255, 0.12)",
        "--st-badge-fg": "#0a84ff",
        "--st-badge-border": "1px solid rgba(10, 132, 255, 0.25)",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#0a84ff",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow":
          "0 8px 20px rgba(10, 132, 255, 0.35), inset 0 1px 0 rgba(255,255,255,0.4)",
        "--st-btn-secondary-bg": "rgba(255, 255, 255, 0.5)",
        "--st-btn-secondary-fg": "#1d1d1f",
        "--st-btn-secondary-border": "1px solid rgba(255, 255, 255, 0.8)",
      },
    },
  },
];
