import type { StyleEntry } from "./types";

// 极简排版谱系:靠字号、网格与留白说话的风格。

export const minimalStyles: StyleEntry[] = [
  {
    slug: "swiss",
    name: "Swiss Style",
    nameZh: "瑞士极简",
    group: "minimal",
    aliases: ["国际主义风格", "International Typographic Style", "网格系统风"],
    description:
      "Black on white plus one red: huge type, a strict grid and whitespace do all the talking.",
    descriptionZh: "白底黑字加一点红,大字号、严格网格和留白完成全部表达。",
    bestFor: "Content sites, portfolios, editorial publications, B2B corporate sites",
    bestForZh: "内容型网站、作品集、出版与编辑类站点、B2B 企业官网",
    promptZh:
      "请用瑞士极简 / 国际主义(Swiss Style)风格设计这个页面:纯白背景、近黑文字,全站只用一个强调色(经典是红色);标题用非常大的无衬线字体(Helvetica / Inter 一类),字重 700、字距收紧(约 -0.03em),和正文形成 4 倍以上的大小反差;严格按网格左对齐,大量留白;区块之间用 1px 黑色细线分隔;按钮是直角的黑色实色矩形或纯文字链接;小标签用大写字母加宽字距。禁止:阴影、渐变、圆角、装饰性插画和图形、第二种强调色、居中排版(保持左对齐网格)。",
    promptEn:
      "Design this page in Swiss / International Typographic Style: pure white background, near-black text, exactly one accent color (classic Swiss red). Headlines use a very large sans-serif (Helvetica / Inter family) at weight 700 with tight letter-spacing (~-0.03em), at least 4x the body size. Left-align everything on a strict grid with generous whitespace; separate sections with 1px black hairlines. Buttons are sharp-cornered solid black rectangles or plain text links; small labels are uppercase with wide tracking. Forbidden: shadows, gradients, rounded corners, decorative illustrations, a second accent color, and centered layouts — stay left-aligned on the grid.",
    recipeZh: [
      "纯白底 + 近黑字 + 唯一强调红,三种颜色封顶",
      "标题字号 ≥4 倍正文,letter-spacing 约 -0.03em",
      "严格网格左对齐,留白本身就是设计",
      "1px 黑色细线分隔区块,代替卡片和阴影",
      "border-radius: 0,一切直角;小标签大写 + 宽字距",
    ],
    recipe: [
      "Pure white + near-black + one Swiss red — three colors, hard cap",
      "Headline ≥4x body size, letter-spacing around -0.03em",
      "Strict left-aligned grid; whitespace is the design",
      "1px black hairlines separate sections — no cards, no shadows",
      "border-radius: 0 everywhere; small labels uppercase with wide tracking",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#ffffff",
        "--st-page-fg": "#0a0a0a",
        "--st-muted": "#525252",
        "--st-card-bg": "#fafafa",
        "--st-card-border": "1px solid #0a0a0a",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #0a0a0a",
        "--st-accent": "#e11d2e",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "-0.03em",
        "--st-badge-bg": "transparent",
        "--st-badge-fg": "#e11d2e",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.14em",
        "--st-btn-primary-bg": "#0a0a0a",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid #0a0a0a",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#0a0a0a",
        "--st-btn-secondary-border": "1px solid #0a0a0a",
      },
    },
  },
  {
    slug: "minimalism",
    name: "Minimalism",
    nameZh: "极简主义",
    group: "minimal",
    aliases: ["极简风", "Minimal", "性冷淡风", "Minimalist Design"],
    description:
      "A softer, more universal minimalism than Swiss style — no strict grid or red accent, just generous whitespace and restrained grayscale that hands focus back to the content.",
    descriptionZh:
      "比瑞士风更柔和、更通用的极简:不靠网格和红色说话,靠大量留白和克制的灰阶把视线交还给内容。",
    bestFor: "SaaS landing pages, personal portfolios, note-taking / productivity apps, boutique product sites",
    bestForZh: "SaaS 产品落地页、个人作品集、笔记 / 效率类工具、精品电商产品页",
    promptZh:
      "请用极简主义(Minimalism)风格设计这个页面:近白背景 #fcfcfc,正文深灰 #171717,次要文字中灰 #737373;卡片用浅灰块 #f4f4f5,不设可见描边,大圆角 12px(小尺寸控件用 8px),不用阴影;强调色就是主文字色本身 #171717,不引入品牌色;主按钮纯黑底白字,次按钮透明底配 1px 浅灰描边 #d4d4d4;标题字重 600、字距收紧到 -0.02em,克制但不生硬;区块间用 1px 浅灰分隔线 #e5e5e5 代替卡片阴影。禁止:高饱和色、硬阴影、粗黑描边、超大字号对比、装饰性图形。",
    promptEn:
      "Design this page in minimalism style: a near-white background #fcfcfc, dark gray body text #171717, mid-gray secondary text #737373; cards are soft gray blocks #f4f4f5 with no visible border, large 12px radius (8px for small controls), and no shadow; the accent color is simply the primary text color #171717 — no brand hue; primary buttons are solid black with white text, secondary buttons are transparent with a 1px light-gray border #d4d4d4; headings sit at weight 600 with tight -0.02em tracking, restrained but not harsh; separate sections with a 1px light-gray divider #e5e5e5 instead of card shadows. Forbidden: saturated colors, hard shadows, thick black borders, oversized type contrast, decorative graphics.",
    recipeZh: [
      "body { background:#fcfcfc; color:#171717; }",
      "卡片 background:#f4f4f5; border:1px solid transparent; border-radius:12px(小控件 8px); box-shadow:none;",
      "accent 直接复用主文字色 #171717,不额外引入品牌色",
      "主按钮 background:#171717; color:#fff; 次按钮 background:transparent; border:1px solid #d4d4d4;",
      "分区用 border-bottom:1px solid #e5e5e5,标题 font-weight:600; letter-spacing:-0.02em;",
    ],
    recipe: [
      "body { background:#fcfcfc; color:#171717; }",
      "Card background:#f4f4f5; border:1px solid transparent; border-radius:12px (8px for small controls); box-shadow:none;",
      "Accent reuses the primary text color #171717 — no separate brand hue",
      "Primary button background:#171717; color:#fff; secondary button background:transparent; border:1px solid #d4d4d4;",
      "Sections split with border-bottom:1px solid #e5e5e5; headings font-weight:600; letter-spacing:-0.02em;",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fcfcfc",
        "--st-page-fg": "#171717",
        "--st-muted": "#737373",
        "--st-card-bg": "#f4f4f5",
        "--st-card-border": "1px solid transparent",
        "--st-card-blur": "none",
        "--st-radius-lg": "12px",
        "--st-radius-sm": "8px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #e5e5e5",
        "--st-accent": "#171717",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.02em",
        "--st-badge-bg": "#f4f4f5",
        "--st-badge-fg": "#525252",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0em",
        "--st-btn-primary-bg": "#171717",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid #171717",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#171717",
        "--st-btn-secondary-border": "1px solid #d4d4d4",
      },
    },
  },
  {
    slug: "editorial",
    name: "Editorial",
    nameZh: "杂志编辑风",
    group: "minimal",
    aliases: ["杂志风", "Editorial Design", "报刊排版风", "Magazine Style"],
    description:
      "A warm paper-toned background with serif display headlines and a wine-red accent — the feel of flipping through a well-made indie magazine.",
    descriptionZh: "米白纸感底色配衬线大标题,酒红点缀,像翻开一本考究的独立杂志。",
    bestFor: "Blogs and long-form writing, magazine/newsletter sites, agency portfolios, book/author pages",
    bestForZh: "博客与长文写作平台、杂志 / newsletter 官网、创意机构作品集、书籍或作者主页",
    promptZh:
      "请用杂志编辑风(Editorial)风格设计这个页面:米白纸感背景 #faf7f2,墨黑正文 #1c1a17,次要文字暖灰 #6e675c;标题字体换成衬线 Georgia, \"Times New Roman\", serif,字重 700、字距收紧到 -0.01em,做出排版感;卡片用米黄纸色块 #f4efe6,不设描边,圆角仅 2px,不用阴影;强调色是深酒红 #8c2f39,只用在徽标文字和关键强调处;徽标是透明底酒红字,大写字母加宽字距到 0.16em,像期刊分类标签;主按钮墨黑底米白字直角,次按钮细描边 #d8d0c2;区块间用 1px 米棕分隔线 #d8d0c2,营造版面栏线感。禁止:无衬线大黑体标题、高饱和撞色、硬阴影、大圆角、数字化科技感元素。",
    promptEn:
      "Design this page in editorial (magazine) style: a warm paper background #faf7f2, ink-black body text #1c1a17, warm-gray secondary text #6e675c; set headlines in a serif — Georgia, \"Times New Roman\", serif — at weight 700 with tight -0.01em tracking for a typeset feel; cards are cream paper blocks #f4efe6 with no visible border, only 2px radius, and no shadow; the accent is a deep wine red #8c2f39, reserved for badge text and key emphasis; badges are transparent with wine-red uppercase text at 0.16em tracking, like a journal section tag; primary buttons are sharp-cornered ink black with cream text, secondary buttons get a thin #d8d0c2 outline; separate sections with a 1px tan hairline #d8d0c2 for a printed-column feel. Forbidden: bold sans-serif display headlines, saturated color clashes, hard shadows, large border radii, digital/tech-flavored decoration.",
    recipeZh: [
      "body { background:#faf7f2; color:#1c1a17; }",
      "标题 font-family: Georgia, 'Times New Roman', serif; font-weight:700; letter-spacing:-0.01em;",
      "卡片 background:#f4efe6; border-radius:2px; box-shadow:none; 无描边",
      "accent 只用于 badge 文字和强调:#8c2f39,badge 大写 + letter-spacing:0.16em",
      "分区用 border-bottom:1px solid #d8d0c2,主按钮墨黑底米白字直角",
    ],
    recipe: [
      "body { background:#faf7f2; color:#1c1a17; }",
      "Headings font-family: Georgia, 'Times New Roman', serif; font-weight:700; letter-spacing:-0.01em;",
      "Card background:#f4efe6; border-radius:2px; box-shadow:none; no visible border",
      "Accent reserved for badge text and emphasis: #8c2f39; badge uppercase + letter-spacing:0.16em",
      "Sections split with border-bottom:1px solid #d8d0c2; primary button is sharp-cornered ink black with cream text",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#faf7f2",
        "--st-page-fg": "#1c1a17",
        "--st-muted": "#6e675c",
        "--st-heading-font": 'Georgia, "Times New Roman", serif',
        "--st-card-bg": "#f4efe6",
        "--st-card-border": "1px solid transparent",
        "--st-card-blur": "none",
        "--st-radius-lg": "2px",
        "--st-radius-sm": "2px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #d8d0c2",
        "--st-accent": "#8c2f39",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "transparent",
        "--st-badge-fg": "#8c2f39",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.16em",
        "--st-btn-primary-bg": "#1c1a17",
        "--st-btn-primary-fg": "#faf7f2",
        "--st-btn-primary-border": "1px solid #1c1a17",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#1c1a17",
        "--st-btn-secondary-border": "1px solid #d8d0c2",
      },
    },
  },
  {
    slug: "japanese-minimal",
    name: "Japanese Minimalism",
    nameZh: "日式极简",
    group: "minimal",
    aliases: ["日式极简", "Japandi", "侘寂风", "MUJI 风"],
    description:
      "Warm off-white paper tones with ink-gray text and vermillion used only in tiny doses — restraint so deliberate that the whitespace itself becomes the message.",
    descriptionZh: "暖白纸色配墨灰文字,朱红只点缀在极小面积,克制得近乎留白本身就是内容。",
    bestFor: "Wellness/spa brands, craft & ceramics studios, boutique hospitality sites, MUJI-style product catalogs",
    bestForZh: "疗愈 / spa 品牌官网、手工艺与陶艺工作室、精品民宿 / 酒店站点、MUJI 风格产品目录",
    promptZh:
      "请用日式极简(Japanese Minimalism / Japandi)风格设计这个页面:暖白背景 #f7f5f0,墨灰正文 #2b2b2b,次要文字浅灰褐 #8a857c;卡片与页面同色 #f7f5f0,只用 1px 细边 #e6e0d4 做区隔,圆角仅 4px,绝不用阴影;强调色朱红 #b5432a 只出现在极小面积——徽标文字、数字这类点缀处,大面积绝不铺色;徽标透明底朱红字,大写字母加宽字距到 0.2em;标题字重偏轻(500),字距略微放宽到 0.02em,留出呼吸感,而非常规极简的收紧字距;主按钮墨黑底暖白字直角,次按钮透明配墨色细框;区块间用 1px 浅褐分隔线 #e6e0d4。禁止:大面积朱红或任何高饱和色块、硬阴影、粗描边、繁复装饰、超粗字重标题。",
    promptEn:
      "Design this page in Japanese minimalism (Japandi) style: warm off-white background #f7f5f0, ink-gray body text #2b2b2b, soft taupe secondary text #8a857c; cards match the page color #f7f5f0, separated only by a thin 1px border #e6e0d4, with just 4px radius and never a shadow; the accent vermillion #b5432a appears only in tiny doses — badge text, small numerals — never as a large color block; badges are transparent with uppercase vermillion text at 0.2em tracking; headings use a light weight (500) with slightly loosened 0.02em tracking for breathing room, the opposite of the usual tight-minimalism move; primary buttons are sharp-cornered ink black with warm-white text, secondary buttons stay transparent with a thin ink outline; separate sections with a 1px taupe hairline #e6e0d4. Forbidden: large vermillion or saturated color blocks, hard shadows, thick borders, ornate decoration, extra-bold display headlines.",
    recipeZh: [
      "body { background:#f7f5f0; color:#2b2b2b; }",
      "卡片 background 与页面同色,仅 border:1px solid #e6e0d4 做区隔;border-radius:4px;box-shadow:none;",
      "accent 朱红 #b5432a 只用于 badge 字色和数字等小面积,不铺大色块",
      "badge 透明底 + 朱红大写字 + letter-spacing:0.2em",
      "标题 font-weight:500(轻),letter-spacing:0.02em(微放宽),制造呼吸感",
    ],
    recipe: [
      "body { background:#f7f5f0; color:#2b2b2b; }",
      "Card background matches the page; only border:1px solid #e6e0d4 marks the edge; border-radius:4px; box-shadow:none;",
      "Accent vermillion #b5432a only appears at small scale — badge text, numerals — never as a large fill",
      "Badge: transparent background + uppercase vermillion text + letter-spacing:0.2em",
      "Headings: font-weight:500 (light), letter-spacing:0.02em (slightly loosened) for breathing room",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#f7f5f0",
        "--st-page-fg": "#2b2b2b",
        "--st-muted": "#8a857c",
        "--st-card-bg": "#f7f5f0",
        "--st-card-border": "1px solid #e6e0d4",
        "--st-card-blur": "none",
        "--st-radius-lg": "4px",
        "--st-radius-sm": "4px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #e6e0d4",
        "--st-accent": "#b5432a",
        "--st-heading-weight": "500",
        "--st-heading-tracking": "0.02em",
        "--st-badge-bg": "transparent",
        "--st-badge-fg": "#b5432a",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.2em",
        "--st-btn-primary-bg": "#2b2b2b",
        "--st-btn-primary-fg": "#f7f5f0",
        "--st-btn-primary-border": "1px solid #2b2b2b",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#2b2b2b",
        "--st-btn-secondary-border": "1px solid #2b2b2b",
      },
    },
  },
];
