import type { StyleEntry } from "./types";

// 混合批次:布局驱动 / 有机手作 / 体系化三支各出两例,凑成第一批「其余」条目。

export const otherStyles: StyleEntry[] = [
  {
    slug: "bento-grid",
    name: "Bento Grid",
    nameZh: "便当格",
    group: "layout",
    aliases: ["便当盒排版", "Bento Box Layout", "苹果发布会风", "宫格卡片风"],
    description:
      "Uneven cards packed edge-to-edge like compartments in a bento box, each cell sized to say exactly one thing.",
    descriptionZh: "大小不一的卡片像便当格拼在一起,每一格只讲一件事,靠格子大小分主次。",
    bestFor:
      "Product launch pages, feature comparison sections, SaaS pricing pages, portfolio highlight grids",
    bestForZh: "产品发布页、功能亮点区块、SaaS 定价页、作品集精选网格",
    promptZh:
      "请用便当格(Bento Grid)风格设计这个页面:浅灰背景 #f5f5f7 上铺一张不规则网格,把内容拆成大小不一的白色卡片(#ffffff),像便当盒的格子一样紧密拼接,一格只讲一个卖点;最大的一格明显占两倍面积,承载主要信息,其余格子按重要性递减;卡片圆角 22px、细边框 1px solid #e8e8ed,只用极轻的投影 0 1px 2px rgba(0,0,0,.04) 做区分,不做强阴影;强调色克制地用一种苹果蓝 #0071e3,按钮做成胶囊形状;标题字重 700、字距收紧 -0.02em;正文灰 #6e6e73 与深灰黑 #1d1d1f 两级足够。禁止:等大小的规整网格(必须大小错落)、强投影或渐变、多种强调色、方角卡片、把所有内容塞进同一格。",
    promptEn:
      "Design this page in a Bento Grid style: an uneven, tightly packed grid of white cards (#ffffff) on a light gray backdrop (#f5f5f7), like compartments in a bento box — each cell states exactly one point. Make the largest cell roughly twice the area of the others to carry the primary message, with the rest sized down by importance. Cards get 22px rounded corners, a hairline 1px solid #e8e8ed border, and only a whisper of shadow (0 1px 2px rgba(0,0,0,.04)) — no heavy drop shadows. Use one restrained Apple-blue accent (#0071e3) and pill-shaped buttons. Headlines are weight 700 with tight -0.02em tracking; two grays (#1d1d1f / #6e6e73) carry the rest of the hierarchy. Forbidden: a uniform equal-size grid (sizes must vary), heavy shadows or gradients, multiple accent colors, sharp square corners, cramming everything into one cell.",
    recipeZh: [
      "grid 用 CSS Grid + grid-column/row-span 让首格跨两列两行,制造大小差",
      "卡片 radius 22px、边框 1px solid #e8e8ed、影子只用 0 1px 2px rgba(0,0,0,.04)",
      "badge 与按钮圆角设为 999px(胶囊),与卡片圆角形成大小对比",
      "强调色只用一种苹果蓝 #0071e3,克制不撞色",
      "标题字重 700、字距 -0.02em;正文用两级灰阶区分层级",
    ],
    recipe: [
      "CSS Grid with column/row spans so the first cell spans 2x2 for visual weight",
      "Cards: 22px radius, 1px solid #e8e8ed border, whisper shadow 0 1px 2px rgba(0,0,0,.04)",
      "Badges and buttons at 999px radius (pill) contrast against the larger card radius",
      "One accent only — Apple blue #0071e3 — never mixed with a second hue",
      "Headlines weight 700 at -0.02em tracking; two gray levels carry the rest of hierarchy",
    ],
    skin: {
      backdrop: "none",
      layout: "bento",
      vars: {
        "--st-page-bg": "#f5f5f7",
        "--st-page-fg": "#1d1d1f",
        "--st-muted": "#6e6e73",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "1px solid #e8e8ed",
        "--st-card-blur": "none",
        "--st-radius-lg": "22px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 1px 2px rgba(0, 0, 0, 0.04)",
        "--st-divider": "1px solid #e8e8ed",
        "--st-accent": "#0071e3",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "-0.02em",
        "--st-badge-bg": "rgba(0, 113, 227, 0.1)",
        "--st-badge-fg": "#0071e3",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#0071e3",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#0071e3",
        "--st-btn-secondary-border": "1px solid #d2d2d7",
      },
    },
  },
  {
    slug: "organic-shapes",
    name: "Organic Shapes",
    nameZh: "有机风",
    group: "organic",
    aliases: ["自然曲面风", "Organic Design", "大地色系", "柔态设计"],
    description:
      "Soft rounded blobs and warm earth tones — every corner curves, nothing points.",
    descriptionZh: "浑圆的曲线块面和温暖大地色,没有一处是尖角。",
    bestFor:
      "Wellness and skincare brands, boutique cafes, children/parenting products, slow-living lifestyle brands",
    bestForZh: "身心健康与护肤品牌、精品咖啡馆、母婴亲子类产品、慢生活方式品牌",
    promptZh:
      "请用有机风(Organic Shapes)风格设计这个页面:奶油底色 #fdf8f0,卡片用米白 #fffdfa,圆角开到 32px(小元素干脆用 999px 全圆),让每张卡片看起来像被打磨过的鹅卵石;阴影用柔和的暖色环境光 0 12px 32px rgba(196,144,100,.16),配 1px solid #f0e4d3 的浅描边;强调色用陶土橙 #d97742,搭配深棕文字 #3d3128 和暖灰 muted #8a7b6c;标题字重 600、字距轻收 -0.01em,不需要很粗;按钮同样是全圆角胶囊;整体给人被阳光晒过的陶罐质感。禁止:任何直角或尖角、冷色调(蓝、灰紫)、高对比黑白、硬边投影、锐利几何图形。",
    promptEn:
      "Design this page in an Organic Shapes style: a cream background (#fdf8f0) with off-white cards (#fffdfa), rounded up to 32px — and fully round (999px) on small elements — so every card reads like a smoothed river stone. Shadows are a soft warm ambient glow (0 12px 32px rgba(196,144,100,.16)) paired with a faint 1px solid #f0e4d3 border. The accent is terracotta (#d97742) against deep brown text (#3d3128) and a warm gray for muted copy (#8a7b6c). Headlines are weight 600 with a slight -0.01em tracking — no need for heavy weight. Buttons are fully rounded pills too, giving the whole page the feel of sun-warmed pottery. Forbidden: any sharp or square corners, cool tones (blue, gray-violet), high-contrast black-and-white, hard-edged drop shadows, sharp geometric shapes.",
    recipeZh: [
      "card radius 32px,按钮/badge 用 999px 全圆角,曲线贯穿全站",
      "投影用暖色扩散光 0 12px 32px rgba(196,144,100,.16),不用冷灰阴影",
      "配色锁定大地色系:奶油底 + 陶土橙强调 + 深棕文字",
      "标题字重只到 600,靠曲线和留白而不是粗字重表达存在感",
      "边框统一 1px solid #f0e4d3,浅到几乎融进底色",
    ],
    recipe: [
      "Card radius 32px; buttons/badges at full 999px round — curves carry the whole system",
      "Shadow uses a warm diffuse glow 0 12px 32px rgba(196,144,100,.16), never cold gray",
      "Palette locked to earth tones: cream base + terracotta accent + deep brown text",
      "Headlines stay at weight 600 — presence comes from curve and whitespace, not boldness",
      "Borders uniformly 1px solid #f0e4d3, faint enough to almost dissolve into the background",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fdf8f0",
        "--st-page-fg": "#3d3128",
        "--st-muted": "#8a7b6c",
        "--st-card-bg": "#fffdfa",
        "--st-card-border": "1px solid #f0e4d3",
        "--st-card-blur": "none",
        "--st-radius-lg": "32px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 12px 32px rgba(196, 144, 100, 0.16)",
        "--st-divider": "1px solid #f0e4d3",
        "--st-accent": "#d97742",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "rgba(217, 119, 66, 0.12)",
        "--st-badge-fg": "#d97742",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#d97742",
        "--st-btn-primary-fg": "#fffdfa",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "#fffdfa",
        "--st-btn-secondary-fg": "#d97742",
        "--st-btn-secondary-border": "1px solid #f0e4d3",
      },
    },
  },
  {
    slug: "hand-drawn",
    name: "Hand-drawn",
    nameZh: "手绘风",
    group: "organic",
    aliases: ["Sketchy", "涂鸦风", "手绘涂鸦", "Doodle Style"],
    description:
      "Wobbly pencil-drawn borders and comic lettering on notebook paper — like a sketch that escaped into a browser.",
    descriptionZh: "歪歪扭扭的铅笔描边和涂鸦字体印在纸白背景上,像一张跑进浏览器的手稿。",
    bestFor:
      "Kids' education products, indie game landing pages, personal blogs and zines, playful event/community sites",
    bestForZh: "儿童教育产品、独立游戏落地页、个人博客与 zine、社区活动类网站",
    promptZh:
      "请用手绘风(Hand-drawn)风格设计这个页面:纸白底色 #fffdf5;卡片用白底配 2px 纯黑手绘描边,四角用不规则的圆角组合(比如 255px 18px 225px 18px / 18px 225px 18px 255px)模拟手抖画出来的边框;标题和正文用手写体字体栈(如 Comic Sans MS / Chalkboard SE);投影模拟铅笔笔触,用生硬的偏移阴影 3px 3px 0 rgba(43,43,43,.75),不做模糊;强调色用蜡笔蓝 #4a7cff,标签用便签黄 #fff3a3 配黑字;文字主色 #2b2b2b,次要 #6b6558;主按钮蜡笔蓝底白字并保持同样不规则圆角,次按钮白底黑框。禁止:标准无衬线字体、规整的正圆角或直角、任何模糊柔和阴影、极简留白式排版、冷灰色系。",
    promptEn:
      "Design this page in a hand-drawn style: a paper-white background (#fffdf5); cards are white with a 2px solid black hand-sketched border, using an irregular rounded-corner combo (e.g. 255px 18px 225px 18px / 18px 225px 18px 255px) so the outline looks like it wobbled off a pencil. Headings and body copy use a handwritten font stack (Comic Sans MS / Chalkboard SE). Shadows fake a pencil stroke — a hard offset 3px 3px 0 rgba(43,43,43,.75), never blurred. The accent is crayon blue (#4a7cff), tags are sticky-note yellow (#fff3a3) with black text. Primary text is #2b2b2b, muted is #6b6558. The primary button is crayon-blue with white text and the same irregular rounded corners; the secondary button is white with a black outline. Forbidden: standard clean sans-serif fonts, perfectly circular or perfectly square corners, any blurred or soft shadow, minimalist whitespace-driven layouts, cold gray palettes.",
    recipeZh: [
      "border-radius 用不对称四值组合(如 255px 18px 225px 18px / 18px 225px 18px 255px)模拟手抖",
      "字体栈换成手写体:'Comic Sans MS', 'Chalkboard SE', cursive",
      "阴影用零模糊硬偏移 3px 3px 0 rgba(43,43,43,.75),不用 blur",
      "描边固定 2px solid #2b2b2b,粗细接近马克笔笔触",
      "点缀色用便签黄 #fff3a3 做 badge,蜡笔蓝 #4a7cff 做强调,避免高级灰",
    ],
    recipe: [
      "border-radius as an asymmetric four-value combo (e.g. 255px 18px 225px 18px / 18px 225px 18px 255px) to fake a wobbly hand-drawn line",
      "Swap the font stack for handwriting: 'Comic Sans MS', 'Chalkboard SE', cursive",
      "Shadows are zero-blur hard offsets, 3px 3px 0 rgba(43,43,43,.75) — never blurred",
      "Borders fixed at 2px solid #2b2b2b, thick enough to read as a marker stroke",
      "Accents: sticky-note yellow #fff3a3 for badges, crayon blue #4a7cff for emphasis — skip sophisticated grays",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fffdf5",
        "--st-page-fg": "#2b2b2b",
        "--st-muted": "#6b6558",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "2px solid #2b2b2b",
        "--st-card-blur": "none",
        "--st-radius-lg": "255px 18px 225px 18px / 18px 225px 18px 255px",
        "--st-radius-sm": "150px 12px 130px 12px / 12px 130px 12px 150px",
        "--st-shadow": "3px 3px 0 rgba(43, 43, 43, 0.75)",
        "--st-divider": "2px solid #2b2b2b",
        "--st-accent": "#4a7cff",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "#fff3a3",
        "--st-badge-fg": "#2b2b2b",
        "--st-badge-border": "2px solid #2b2b2b",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#4a7cff",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "2px solid #2b2b2b",
        "--st-btn-primary-shadow": "3px 3px 0 rgba(43, 43, 43, 0.75)",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#2b2b2b",
        "--st-btn-secondary-border": "2px solid #2b2b2b",
        "--st-font": '"Comic Sans MS", "Chalkboard SE", cursive',
      },
    },
  },
  {
    slug: "dopamine-colors",
    name: "Dopamine Colors",
    nameZh: "多巴胺配色",
    group: "organic",
    aliases: ["快乐色彩风", "Dopamine Dressing UI", "糖果色风", "高饱和配色风"],
    description:
      "Candy-saturated color blocks and oversized rounded shapes turned up to maximum joy.",
    descriptionZh: "高饱和糖果色块配上放大的圆角形状,把快乐值直接拉满。",
    bestFor:
      "Gen-Z consumer apps, festival and event pages, youth fashion e-commerce, creator/community platforms",
    bestForZh: "Z 世代消费类应用、节庆活动页面、年轻潮流电商、创作者社区平台",
    promptZh:
      "请用多巴胺配色(Dopamine Colors)风格设计这个页面:暖白底色 #fff7ec;卡片纯白,大圆角 20px,小元素直接 999px 全圆;强调色用高饱和玫红 #ff477e,标签用橙色 #ff9f1c 配白字胶囊;投影带彩色扩散光 0 10px 24px rgba(255,71,126,.18),不用灰黑阴影;标题字重拉到 800、字距收紧 -0.01em,营造有力量的快乐感;文字主色 #33202a,次要 #8a6470,都带一点暖调而不是纯灰;主按钮玫红底白字胶囊,次按钮白底玫红字玫红描边。禁止:任何低饱和莫兰迪色、纯黑白灰配色、细字重标题、尖角、灰色投影。",
    promptEn:
      "Design this page in a Dopamine Colors style: a warm off-white background (#fff7ec) with pure white cards at a generous 20px radius — small elements go fully round at 999px. The accent is a saturated hot pink (#ff477e); tags are orange (#ff9f1c) white-text pills. Shadows carry a colorful diffuse glow (0 10px 24px rgba(255,71,126,.18)) — never gray or black. Headlines go all the way to weight 800 with tight -0.01em tracking for an energetic, joyful punch. Primary text is #33202a and muted is #8a6470, both warm-tinted rather than neutral gray. The primary button is hot-pink with white text as a pill; the secondary is white with a hot-pink label and hot-pink outline. Forbidden: any desaturated Morandi palette, black/white/gray-only color schemes, thin headline weights, sharp corners, gray shadows.",
    recipeZh: [
      "card radius 20px、按钮/badge 999px 全圆,大圆角是快乐感的骨架",
      "投影带色:0 10px 24px rgba(255,71,126,.18),阴影本身也要「有颜色」",
      "主强调玫红 #ff477e + 辅助橙 #ff9f1c 两色对撞,不引入第三种强调色",
      "标题字重拉满到 800,字距略收 -0.01em",
      "文字灰阶也带暖调(#33202a / #8a6470),避免纯中性灰拉低情绪",
    ],
    recipe: [
      "Card radius 20px, buttons/badges fully round at 999px — big radii are the skeleton of the joy",
      "Shadows carry color too: 0 10px 24px rgba(255,71,126,.18), never neutral gray",
      "Two accents collide: hot pink #ff477e as primary, orange #ff9f1c as secondary — no third hue",
      "Headlines pushed to weight 800 with tight -0.01em tracking",
      "Even the gray scale is warm-tinted (#33202a / #8a6470) to avoid flattening the mood",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fff7ec",
        "--st-page-fg": "#33202a",
        "--st-muted": "#8a6470",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "1px solid #ffe3d3",
        "--st-card-blur": "none",
        "--st-radius-lg": "20px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 10px 24px rgba(255, 71, 126, 0.18)",
        "--st-divider": "1px solid #ffe3d3",
        "--st-accent": "#ff477e",
        "--st-heading-weight": "800",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#ff9f1c",
        "--st-badge-fg": "#ffffff",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#ff477e",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#ff477e",
        "--st-btn-secondary-border": "1px solid #ff477e",
      },
    },
  },
  {
    slug: "material-design",
    name: "Material Design 3",
    nameZh: "材料设计",
    group: "system",
    aliases: ["Material You", "M3", "谷歌设计语言", "Material Design"],
    description:
      "Google's tonal surfaces and pill-shaped controls — elevation and color roles do the structural work.",
    descriptionZh: "谷歌的色调化表面与胶囊控件,靠层级投影和色彩角色搭骨架。",
    bestFor:
      "Android/cross-platform apps, Google-ecosystem tools, enterprise admin consoles, productivity SaaS dashboards",
    bestForZh: "Android / 跨端应用、谷歌生态工具、企业后台管理系统、效率类 SaaS 仪表盘",
    promptZh:
      "请用材料设计(Material Design 3 / Material You)风格设计这个页面:浅灰底 #fafafa;卡片纯白 #ffffff,圆角 16px,按钮和标签用 999px 胶囊(M3 的标志性控件形状);投影用双层高度阴影模拟真实光源:0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24);强调色用 M3 紫 #6750a4;标签用浅紫色调背景 rgba(103,80,164,.12) 配紫字(tonal 色调容器的做法);标题字重保持常规 500,不刻意加粗,靠色彩角色和层级阴影分主次;文字主色 #1c1b1f,次要 #49454f;主按钮紫底白字胶囊,次按钮透明底紫字配 1px solid #79747e 描边(M3 的 outlined button)。禁止:硬阴影(box-shadow 零扩散的生硬偏移)、方角控件、超粗标题字重、单一纯黑投影、忽略色调容器直接用纯色块做标签。",
    promptEn:
      "Design this page in a Material Design 3 (Material You) style: a light gray background (#fafafa) with pure white cards (#ffffff) at 16px radius, while buttons and tags use the signature 999px pill shape. Shadows use M3's two-layer elevation to fake a real light source: 0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24). The accent is M3 purple (#6750a4); tags use a tonal container — a light purple tint background rgba(103,80,164,.12) with purple text — rather than a flat solid fill. Headlines stay at a regular weight of 500; hierarchy comes from color roles and elevation, not boldness. Primary text is #1c1b1f, muted is #49454f. The primary button is purple-filled with white text as a pill; the secondary is an outlined button — transparent background, purple text, 1px solid #79747e border. Forbidden: hard zero-blur offset shadows, square-cornered controls, extra-bold headline weights, single flat black shadows, and flat solid-color tags that skip the tonal-container pattern.",
    recipeZh: [
      "投影用双层 elevation:0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24)",
      "按钮/标签统一 999px 胶囊,这是 M3 最强的形状识别特征",
      "badge 用 tonal container 做法:强调色 12% 透明度底色 + 强调色本身做字色",
      "强调色只用 M3 紫 #6750a4,不引入第二种品牌色",
      "标题字重保持 500(regular),层级靠色彩角色和阴影而不是加粗",
    ],
    recipe: [
      "Two-layer elevation shadow: 0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24)",
      "Buttons and tags share the 999px pill shape — M3's strongest shape signature",
      "Badges follow the tonal-container pattern: accent at 12% opacity as fill, full accent as text",
      "One accent only — M3 purple #6750a4 — no second brand color",
      "Headlines stay at weight 500 (regular); hierarchy comes from color role and elevation, not boldness",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fafafa",
        "--st-page-fg": "#1c1b1f",
        "--st-muted": "#49454f",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "1px solid transparent",
        "--st-card-blur": "none",
        "--st-radius-lg": "16px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)",
        "--st-divider": "1px solid #e7e0ec",
        "--st-accent": "#6750a4",
        "--st-heading-weight": "500",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "rgba(103, 80, 164, 0.12)",
        "--st-badge-fg": "#6750a4",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#6750a4",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#6750a4",
        "--st-btn-secondary-border": "1px solid #79747e",
      },
    },
  },
  {
    slug: "flat-design",
    name: "Flat Design 2.0",
    nameZh: "扁平化 2.0",
    group: "system",
    aliases: ["扁平化", "Flat UI", "极简扁平风", "Flat Design"],
    description:
      "Solid color blocks and zero shadow — every surface stays perfectly flat on the page.",
    descriptionZh: "纯色色块与零投影,每一个表面都老老实实贴在页面上,不装立体。",
    bestFor:
      "B2B SaaS marketing sites, internal admin tools, mobile app onboarding screens, icon/UI kit showcases",
    bestForZh: "B2B SaaS 官网、内部管理后台、移动应用引导页、图标与 UI 组件展示页",
    promptZh:
      "请用扁平化 2.0(Flat Design 2.0)风格设计这个页面:纯白底 #ffffff;卡片用浅灰蓝色块 #f1f5f9 铺底,不描边或描边设为透明,圆角克制在 8px(小元素 6px);彻底不用阴影,box-shadow: none;强调色用明快的蓝 #3b82f6,做纯色块而不是渐变;标签用蓝底白字纯色矩形;文字主色近黑 #0f172a,次要 #64748b;主按钮蓝底白字,次按钮用浅灰蓝 #e2e8f0 底配深字,都不加描边和阴影;标题字重 700、字距轻收 -0.01em,靠色块对比而不是立体效果分层级。禁止:任何渐变、拟物质感(仿皮革/仿纸张纹理)、投影、描边装饰线、圆润的大圆角或全圆角胶囊按钮。",
    promptEn:
      "Design this page in a Flat Design 2.0 style: a pure white background (#ffffff) with light gray-blue card blocks (#f1f5f9), borders removed or set transparent, and radii kept restrained at 8px (6px for small elements). Drop shadows entirely — box-shadow: none everywhere. The accent is a bright blue (#3b82f6) used as flat solid fill, never a gradient. Tags are solid blue rectangles with white text. Primary text is near-black (#0f172a), muted is #64748b. The primary button is solid blue with white text; the secondary uses a light gray-blue fill (#e2e8f0) with dark text — neither gets a border or shadow. Headlines are weight 700 with a slight -0.01em tracking; hierarchy comes from color-block contrast, not any illusion of depth. Forbidden: any gradient, skeuomorphic texture (faux leather, faux paper), drop shadows, decorative border strokes, large rounded corners or fully pill-shaped buttons.",
    recipeZh: [
      "box-shadow 全站设为 none,不留任何立体错觉",
      "卡片靠色块区分(#f1f5f9 vs 白底),而不是描边或投影",
      "圆角克制在 6-8px,拒绝大圆角或全圆角胶囊",
      "强调色 #3b82f6 只用纯色填充,不叠加渐变或光泽",
      "标签和按钮都是纯色矩形,颜色对比就是唯一的层级工具",
    ],
    recipe: [
      "box-shadow: none everywhere — no illusion of depth anywhere on the page",
      "Cards are distinguished by flat color blocks (#f1f5f9 vs white), not borders or shadows",
      "Radii stay restrained at 6-8px — no large rounds, no pill-shaped buttons",
      "The accent #3b82f6 is always a flat solid fill, never a gradient or gloss",
      "Tags and buttons are solid-color rectangles — color contrast is the only hierarchy tool",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#ffffff",
        "--st-page-fg": "#0f172a",
        "--st-muted": "#64748b",
        "--st-card-bg": "#f1f5f9",
        "--st-card-border": "1px solid transparent",
        "--st-card-blur": "none",
        "--st-radius-lg": "8px",
        "--st-radius-sm": "6px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #e2e8f0",
        "--st-accent": "#3b82f6",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#3b82f6",
        "--st-badge-fg": "#ffffff",
        "--st-badge-border": "1px solid transparent",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#3b82f6",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid transparent",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "#e2e8f0",
        "--st-btn-secondary-fg": "#0f172a",
        "--st-btn-secondary-border": "1px solid transparent",
      },
    },
  },
];
