import type { StyleEntry } from "./types";

// 粗野反叛谱系:故意打破"精致"的风格。

export const rawStyles: StyleEntry[] = [
  {
    slug: "neubrutalism",
    name: "Neubrutalism",
    nameZh: "新粗野主义",
    group: "raw",
    aliases: ["新野兽派", "Neo-brutalism", "新粗野风"],
    description:
      "Thick black borders, hard offset shadows and clashing candy colors — deliberately unpolished, loudly alive.",
    descriptionZh: "粗黑描边、硬阴影和糖果撞色,故意的「不精致」,张扬得理直气壮。",
    bestFor: "Personal sites, creative studios, playful marketing pages for young brands",
    bestForZh: "个人网站、创意工作室、年轻化品牌的营销落地页",
    promptZh:
      "请用新粗野主义(Neubrutalism)风格设计这个页面:明亮的奶油色底;所有卡片、按钮、输入框都用 2px 纯黑描边,配黑色硬阴影(box-shadow: 4px 4px 0 #111,零模糊);圆角很小(4-8px)或干脆直角;标题用超粗字重(800-900);配色用高饱和糖果色撞色(亮粉、柠檬黄、薄荷绿);hover 时元素朝阴影方向平移几像素、阴影同步缩小,像被物理按下去。禁止:柔和阴影、任何渐变、半透明、细字重、低饱和灰色调、大圆角。",
    promptEn:
      "Design this page in a neubrutalism style: a bright cream background; every card, button and input gets a 2px solid black border with a hard black shadow (box-shadow: 4px 4px 0 #111 — zero blur); corners are sharp or barely rounded (4-8px); headings are extra bold (800-900); clash saturated candy colors (hot pink, lemon yellow, mint). On hover, elements translate a few pixels toward the shadow while the shadow shrinks, so they feel physically pressed. Forbidden: soft shadows, any gradients, transparency, thin font weights, desaturated grays, large border radii.",
    recipeZh: [
      "border: 2px solid #111 + box-shadow: 4px 4px 0 #111(零模糊)",
      "高饱和撞色:奶油底 + 糖果色块(亮粉 / 柠檬黄 / 薄荷绿)",
      "字重 800-900,标题够粗才立得住",
      "hover 平移 translate(2px, 2px) 且阴影缩小,模拟按压",
      "圆角 ≤8px;拒绝透明度和渐变",
    ],
    recipe: [
      "border: 2px solid #111 + box-shadow: 4px 4px 0 #111 (zero blur)",
      "Saturated clashes: cream base + candy blocks (hot pink / lemon / mint)",
      "Font weight 800-900 — headings must be heavy to hold up",
      "Hover: translate(2px, 2px) with a shrinking shadow to fake a press",
      "Radii ≤8px; no transparency, no gradients",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fbf3e4",
        "--st-page-fg": "#111111",
        "--st-muted": "#3f3f3f",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "2px solid #111111",
        "--st-card-blur": "none",
        "--st-radius-lg": "8px",
        "--st-radius-sm": "6px",
        "--st-shadow": "5px 5px 0 0 #111111",
        "--st-divider": "2px solid #111111",
        "--st-accent": "#ff90e8",
        "--st-heading-weight": "900",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#ffdc58",
        "--st-badge-fg": "#111111",
        "--st-badge-border": "2px solid #111111",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.06em",
        "--st-btn-primary-bg": "#ff90e8",
        "--st-btn-primary-fg": "#111111",
        "--st-btn-primary-border": "2px solid #111111",
        "--st-btn-primary-shadow": "4px 4px 0 0 #111111",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#111111",
        "--st-btn-secondary-border": "2px solid #111111",
      },
    },
  },
  {
    slug: "brutalism",
    name: "Brutalism",
    nameZh: "原教旨粗野主义",
    group: "raw",
    aliases: ["粗野主义网页", "Web Brutalism", "原生 HTML 风", "Brutalist Web Design"],
    description:
      "Back to the web's rawest state — pure black, pure white, Times New Roman, none of neubrutalism's candy colors or hard shadows. This is 'raw' in the literal sense.",
    descriptionZh:
      "回到网页最原始的模样:纯白、纯黑、Times New Roman,没有新粗野主义的糖果色和硬阴影 —— 这才是真正意义上的「生」。",
    bestFor: "Design manifestos, anti-design portfolios, text-heavy technical blogs, protest/counter-culture pages",
    bestForZh: "设计宣言 / 反设计作品集、纯文字技术博客、抗议 / 反主流文化页面、极客个人主页",
    promptZh:
      "请用原教旨粗野主义(Brutalism)风格设计这个页面:纯白背景 #ffffff、纯黑文字 #000000,次要文字用 #333333;全局字体退回浏览器默认衬线体 \"Times New Roman\", Times, serif,不引入任何自定义 Web 字体;链接保持原生蓝 #0000ee 加下划线;卡片、按钮统一用 1px solid #000000 的表格感直角边框,圆角为 0;阴影一律 none,不做任何立体或悬浮效果;标题字重 700、字距为 0,只靠字号差异分层级;区块之间用 1px solid #000000 的分隔线代替留白暗示。禁止:任何圆角、阴影、渐变、品牌色或糖果色、自定义字体、多余的悬浮/位移动效。",
    promptEn:
      "Design this page in brutalism (raw web) style: pure white background #ffffff with pure black text #000000, secondary text #333333; fall back to the browser's default serif stack — \"Times New Roman\", Times, serif — no custom web fonts; keep links native blue #0000ee with an underline; give every card and button a 1px solid #000000 table-like square border, zero radius; shadows are always none, no depth or hover-lift effects; headings are weight 700 with zero letter-spacing, relying only on font-size to build hierarchy; separate sections with 1px solid #000000 hairlines instead of whitespace. Forbidden: rounded corners, shadows, gradients, brand or candy colors, custom fonts, decorative hover/transform animations.",
    recipeZh: [
      "body { background:#fff; color:#000; font-family: 'Times New Roman', Times, serif; }",
      "a { color:#0000ee; text-decoration: underline; } —— 不做 hover 变色",
      "卡片/按钮统一 border: 1px solid #000; border-radius: 0; box-shadow: none;",
      "标题 font-weight: 700; letter-spacing: 0; 靠 h1/h2 字号差异建立层级",
      "分区用 border-top: 1px solid #000(divider),不靠卡片阴影或大留白",
    ],
    recipe: [
      "body { background:#fff; color:#000; font-family: 'Times New Roman', Times, serif; }",
      "a { color:#0000ee; text-decoration: underline; } — no hover color change",
      "Cards/buttons share border: 1px solid #000; border-radius: 0; box-shadow: none;",
      "Headings: font-weight: 700; letter-spacing: 0 — hierarchy comes only from h1/h2 font-size",
      "Sections split with border-top: 1px solid #000 (divider), not card shadows or big whitespace",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#ffffff",
        "--st-page-fg": "#000000",
        "--st-muted": "#333333",
        "--st-font": '"Times New Roman", Times, serif',
        "--st-card-bg": "#ffffff",
        "--st-card-border": "1px solid #000000",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "none",
        "--st-divider": "1px solid #000000",
        "--st-accent": "#0000ee",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "#000000",
        "--st-badge-fg": "#ffffff",
        "--st-badge-border": "1px solid #000000",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0em",
        "--st-btn-primary-bg": "#000000",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid #000000",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#000000",
        "--st-btn-secondary-border": "1px solid #000000",
      },
    },
  },
  {
    slug: "maximalism",
    name: "Maximalism",
    nameZh: "极繁主义",
    group: "raw",
    aliases: ["极繁主义", "Maximalism", "More is More", "反极简风"],
    description:
      "A violet gradient backdrop, lemon-yellow cards and colorful hard shadows — the exact opposite of 'less is more': more is more.",
    descriptionZh: "紫色渐变打底、柠檬黄卡片撞彩色硬阴影,把「少即是多」整个反过来说 —— 多即是多。",
    bestFor: "Youth culture brands, music/festival sites, playful SaaS marketing, portfolio sites craving attention",
    bestForZh: "潮流文化品牌、音乐节 / 艺术活动官网、活泼调性的 SaaS 营销页、渴望被注意到的个人作品集",
    promptZh:
      "请用极繁主义(Maximalism)风格设计这个页面:整页背景用亮紫渐变 linear-gradient(160deg, #6a2ff7 0%, #8b3df5 100%),正文用白色,次要文字用半透明白 rgba(255,255,255,.75);卡片用高饱和柠檬黄 #ffe14d,配 3px 实色深紫边框 #16003b,圆角 12px,卡片内文字改用深紫 #16003b 保证对比;所有卡片、按钮统一用彩色硬阴影 box-shadow: 6px 6px 0 0 #ff2d78,零模糊;强调色用品红 #ff2d78,大量用于按钮、图标块和数字;徽标(badge)用青绿色 #2de1c2 底配黑字,大写字母加宽字距;标题字重给到 900,营造塞满版面的视觉密度,元素之间尽量不留呼吸空间。禁止:大面积留白、单一主色调、纤细字重、性冷淡极简排版、柔和渐变或低饱和莫兰迪色。",
    promptEn:
      "Design this page in maximalism style: a bright violet gradient page background linear-gradient(160deg, #6a2ff7 0%, #8b3df5 100%), white body text, semi-transparent white rgba(255,255,255,.75) for secondary text; cards in saturated lemon yellow #ffe14d with a 3px solid deep-violet border #16003b, 12px radius, and deep-violet #16003b text inside cards for contrast; every card and button gets a colorful hard shadow box-shadow: 6px 6px 0 0 #ff2d78 with zero blur; the accent is hot magenta #ff2d78, splashed across buttons, icon blocks and numbers; badges are cyan #2de1c2 with black text, uppercase with wide tracking; headings sit at font-weight 900, and elements are packed tight with almost no breathing room. Forbidden: generous whitespace, a single dominant hue, thin font weights, minimalist restraint, soft gradients or desaturated Morandi tones.",
    recipeZh: [
      "page 背景 linear-gradient(160deg, #6a2ff7 0%, #8b3df5 100%),正文 color:#fff",
      "卡片 background:#ffe14d;border:3px solid #16003b;border-radius:12px,卡内文字 color:#16003b(不继承页面的白色)",
      "box-shadow: 6px 6px 0 0 #ff2d78,卡片/按钮统一零模糊硬阴影",
      "badge background:#2de1c2; color:#000; text-transform:uppercase; letter-spacing:0.06em",
      "标题 font-weight:900,letter-spacing 收紧到 -0.02em,元素间距压缩制造拥挤感",
    ],
    recipe: [
      "Page background: linear-gradient(160deg, #6a2ff7 0%, #8b3df5 100%); body color:#fff",
      "Card background:#ffe14d; border:3px solid #16003b; border-radius:12px; text inside cards switches to color:#16003b instead of inheriting the page's white",
      "box-shadow: 6px 6px 0 0 #ff2d78 — cards and buttons share the same zero-blur hard shadow",
      "Badge background:#2de1c2; color:#000; text-transform:uppercase; letter-spacing:0.06em",
      "Headings: font-weight:900; letter-spacing tightened to -0.02em; compress spacing between elements for density",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "linear-gradient(160deg, #6a2ff7 0%, #8b3df5 100%)",
        "--st-page-fg": "#ffffff",
        "--st-muted": "rgba(255,255,255,.75)",
        "--st-card-bg": "#ffe14d",
        "--st-card-fg": "#16003b",
        "--st-card-muted": "rgba(22, 0, 59, 0.75)",
        "--st-card-border": "3px solid #16003b",
        "--st-card-blur": "none",
        "--st-radius-lg": "12px",
        "--st-radius-sm": "8px",
        "--st-shadow": "6px 6px 0 0 #ff2d78",
        "--st-divider": "3px solid #16003b",
        "--st-accent": "#ff2d78",
        "--st-heading-weight": "900",
        "--st-heading-tracking": "-0.02em",
        "--st-badge-bg": "#2de1c2",
        "--st-badge-fg": "#000000",
        "--st-badge-border": "2px solid #16003b",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.06em",
        "--st-btn-primary-bg": "#ff2d78",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "3px solid #16003b",
        "--st-btn-primary-shadow": "6px 6px 0 0 #16003b",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#ffffff",
        "--st-btn-secondary-border": "3px solid #ffffff",
      },
    },
  },
];
