import type { StyleEntry } from "./types";

// 复古流行谱系:从千禧糖果到 8-bit 像素,把某个年代的屏幕质感重新做成皮肤。

export const retroPopStyles: StyleEntry[] = [
  {
    slug: "y2k",
    name: "Y2K",
    nameZh: "千禧风",
    group: "retro",
    aliases: ["千禧风", "Y2K Aesthetic", "千禧辣妹风", "Cyber Y2K"],
    description:
      "Brushed-chrome gradients, candy-pink badges and glossy capsule buttons — the millennium's idea of the future.",
    descriptionZh: "银色金属渐变配糖果粉徽标,胶囊按钮泛着光泽,是千禧年想象中的未来感。",
    bestFor: "Fashion/beauty landing pages, music artist sites, Gen-Z social apps, nostalgia-driven product drops",
    bestForZh: "美妆时尚落地页、音乐人个人站、Z世代社交产品、怀旧限定商品页",
    promptZh:
      "请用千禧风(Y2K)风格设计这个页面:整页底色用银色金属渐变 linear-gradient(135deg, #dfe3f0 0%, #f6f7fb 50%, #cfd6ea 100%);卡片用半透明白 rgba(255,255,255,.7) 叠 1px solid #aab4d4 描边,营造磨砂金属质感;大卡片圆角 24px,按钮 / 徽标用 999px 全胶囊圆角;主按钮亮蓝 #3d7bff 底白字,配光泽感投影 0 6px 14px rgba(61,123,255,.4);徽标用糖果粉 #ff8ad8 底配深紫 #4a0e3a 字;正文字色 #1f2544,次要文字 #5a6285;标题字重 700,略带未来感但不夸张;背景叠加流光光晕层增强科技糖果氛围。禁止:磨砂玻璃过度模糊到看不清文字、纯黑纯白无过渡的高对比、极简线框风、粗野手绘涂鸦、任何做旧做脏的复古滤镜。",
    promptEn:
      "Design this page in Y2K style: wash the whole page in a silver metallic gradient linear-gradient(135deg, #dfe3f0 0%, #f6f7fb 50%, #cfd6ea 100%); cards sit on frosted translucent white rgba(255,255,255,.7) with a 1px solid #aab4d4 edge for a brushed-chrome feel; large cards use 24px rounded corners while buttons and badges go full capsule at 999px; the primary button is bright blue #3d7bff on white text with a glossy drop shadow 0 6px 14px rgba(61,123,255,.4); badges pair candy pink #ff8ad8 with deep plum #4a0e3a text; body copy sits at #1f2544, secondary text at #5a6285; headings carry weight 700 for a light futuristic edge; layer a soft glow behind the content to push the tech-candy mood. Forbidden: over-blurred frosted glass that swallows legibility, stark black-and-white high contrast, minimalist wireframe styling, raw hand-drawn doodles, any aged/grunge retro filter.",
    recipeZh: [
      "底色银色金属渐变 linear-gradient(135deg, #dfe3f0, #f6f7fb, #cfd6ea)",
      "卡片 rgba(255,255,255,.7) + 1px solid #aab4d4,营造磨砂金属感",
      "大圆角 24px(卡片)+ 999px 胶囊(按钮/徽标)",
      "主按钮亮蓝 #3d7bff 白字 + 光泽阴影 0 6px 14px rgba(61,123,255,.4)",
      "徽标糖果粉 #ff8ad8 底配深紫 #4a0e3a 字,搭配流光背景",
    ],
    recipe: [
      "Base gradient linear-gradient(135deg, #dfe3f0, #f6f7fb, #cfd6ea) for the metallic silver ground",
      "Cards use rgba(255,255,255,.7) fill with 1px solid #aab4d4 border for brushed chrome",
      "Large radius 24px on cards, full 999px capsule on buttons/badges",
      "Primary button bright blue #3d7bff on white with glossy shadow 0 6px 14px rgba(61,123,255,.4)",
      "Badges pair candy pink #ff8ad8 with deep plum #4a0e3a text; layer a soft glow backdrop",
    ],
    skin: {
      backdrop: "aurora",
      vars: {
        "--st-page-bg": "linear-gradient(135deg, #dfe3f0 0%, #f6f7fb 50%, #cfd6ea 100%)",
        "--st-page-fg": "#1f2544",
        "--st-muted": "#5a6285",
        "--st-card-bg": "rgba(255,255,255,.7)",
        "--st-card-border": "1px solid #aab4d4",
        "--st-card-blur": "blur(10px)",
        "--st-radius-lg": "24px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 8px 24px rgba(61,123,255,.18)",
        "--st-divider": "1px solid #aab4d4",
        "--st-accent": "#3d7bff",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "#ff8ad8",
        "--st-badge-fg": "#4a0e3a",
        "--st-badge-border": "1px solid rgba(74,14,58,.35)",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.06em",
        "--st-btn-primary-bg": "#3d7bff",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow": "0 6px 14px rgba(61,123,255,.4)",
        "--st-btn-secondary-bg": "rgba(255,255,255,.7)",
        "--st-btn-secondary-fg": "#3d7bff",
        "--st-btn-secondary-border": "1px solid #3d7bff",
      },
    },
  },
  {
    slug: "vaporwave",
    name: "Vaporwave",
    nameZh: "蒸汽波",
    group: "retro",
    aliases: ["蒸汽波", "Vaporwave", "80s 复古未来", "Synthwave"],
    description:
      "Deep-purple dusk, a neon grid horizon and pink-on-cyan glow — an 80s arcade sunset frozen in CSS.",
    descriptionZh: "深紫暮色配霓虹网格地平线,粉青对撞发着光,像被冻结的 80 年代街机落日。",
    bestFor: "Music/DJ event pages, indie game landing pages, streetwear drops, nightlife brand microsites",
    bestForZh: "音乐/DJ 活动页、独立游戏落地页、街头潮牌限定页、夜生活品牌微站",
    promptZh:
      "请用蒸汽波(Vaporwave)风格设计这个页面:整页底色用深紫渐变 linear-gradient(180deg, #1a0b3b 0%, #3c1a78 100%),背景叠加霓虹网格地平线;卡片用半透明深紫 rgba(30,10,70,.55) 填充,配青色描边 1px solid rgba(1,205,254,.5);强调色用霓虹粉 #ff71ce,搭配青色 #01cdfe 做次强调;标题全部大写(text-transform: uppercase),字重 700、字间距拉宽到 0.08em,营造合成器美学;徽标用青色底配深紫字 #1a0b3b,直角矩形;主按钮粉底深紫字,四周叠加霓虹光晕 box-shadow: 0 0 24px rgba(255,113,206,.35);分隔线用 1px solid rgba(1,205,254,.35) 的细青线。禁止:任何暖色调(橙、棕、大地色)、无衬线极简白底、柔和马卡龙配色、圆润卡通描边、纸质纹理或胶片颗粒滤镜。",
    promptEn:
      "Design this page in Vaporwave style: base the page on a deep-purple vertical gradient linear-gradient(180deg, #1a0b3b 0%, #3c1a78 100%) with a neon grid horizon layered behind the content; cards fill with translucent deep purple rgba(30,10,70,.55) and a cyan edge 1px solid rgba(1,205,254,.5); the primary accent is neon pink #ff71ce with cyan #01cdfe as the secondary accent; headings are fully uppercase, weight 700, tracked out to 0.08em for that synth-aesthetic feel; badges pair cyan fills with deep-purple #1a0b3b text in sharp rectangles; the primary button is pink with deep-purple text wrapped in a neon glow box-shadow: 0 0 24px rgba(255,113,206,.35); dividers are thin cyan hairlines 1px solid rgba(1,205,254,.35). Forbidden: any warm palette (orange, brown, earth tones), minimalist white backgrounds, soft pastel macaron colors, rounded cartoonish outlines, paper texture or film-grain filters.",
    recipeZh: [
      "底色深紫渐变 linear-gradient(180deg, #1a0b3b, #3c1a78)+ 霓虹网格背景",
      "卡片 rgba(30,10,70,.55) + 青色描边 1px solid rgba(1,205,254,.5)",
      "强调色霓虹粉 #ff71ce + 次强调青 #01cdfe",
      "标题 uppercase、字重 700、字间距 0.08em",
      "主按钮粉底深紫字 + 霓虹光晕 0 0 24px rgba(255,113,206,.35);圆角收紧到 6px",
    ],
    recipe: [
      "Deep-purple gradient linear-gradient(180deg, #1a0b3b, #3c1a78) plus a neon grid backdrop",
      "Cards use rgba(30,10,70,.55) fill with cyan edge 1px solid rgba(1,205,254,.5)",
      "Neon pink #ff71ce as primary accent, cyan #01cdfe as secondary",
      "Headings uppercase, weight 700, tracking 0.08em",
      "Primary button pink on deep-purple text with neon glow 0 0 24px rgba(255,113,206,.35); tight 6px radius",
    ],
    skin: {
      backdrop: "grid",
      vars: {
        "--st-page-bg": "linear-gradient(180deg, #1a0b3b 0%, #3c1a78 100%)",
        "--st-page-fg": "#ffffff",
        "--st-muted": "rgba(255,255,255,.65)",
        "--st-card-bg": "rgba(30,10,70,.55)",
        "--st-card-border": "1px solid rgba(1,205,254,.5)",
        "--st-card-blur": "blur(4px)",
        "--st-radius-lg": "6px",
        "--st-radius-sm": "6px",
        "--st-shadow": "0 0 24px rgba(255,113,206,.35)",
        "--st-divider": "1px solid rgba(1,205,254,.35)",
        "--st-accent": "#ff71ce",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0.08em",
        "--st-heading-transform": "uppercase",
        "--st-badge-bg": "#01cdfe",
        "--st-badge-fg": "#1a0b3b",
        "--st-badge-border": "none",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.08em",
        "--st-btn-primary-bg": "#ff71ce",
        "--st-btn-primary-fg": "#1a0b3b",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow": "0 0 24px rgba(255,113,206,.35)",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#01cdfe",
        "--st-btn-secondary-border": "1px solid rgba(1,205,254,.6)",
      },
    },
  },
  {
    slug: "pixel-art",
    name: "Pixel Art",
    nameZh: "像素风",
    group: "retro",
    aliases: ["像素风", "8-bit", "Pixel Art", "红白机风"],
    description:
      "Chunky black outlines, monospace type and zero-blur hard shadows — a sprite sheet rendered as a webpage.",
    descriptionZh: "粗黑直角描边、等宽字体和零模糊硬阴影,像一张精灵图被渲染成了网页。",
    bestFor: "Indie game portfolios, retro-tech product pages, hackathon/dev-tool marketing, arcade-themed events",
    bestForZh: "独立游戏作品集、复古科技产品页、黑客松/开发者工具营销页、街机主题活动页",
    promptZh:
      "请用像素风(Pixel Art)风格设计这个页面:整页底色用深夜蓝 #26233a;卡片用深灰紫 #1f1d2e 填充,配 3px solid #0c0a14 的粗直角描边,圆角一律为 0;全局字体换成等宽字体 \"Courier New\", ui-monospace, monospace,强化像素游戏感;强调色用荧光绿 #7fff6b;标题全部大写、字重 700、字间距 0.04em;徽标用荧光绿底配纯黑字,直角矩形,不带描边;主按钮荧光绿底黑字,配硬阴影 box-shadow: 4px 4px 0 0 #0c0a14(零模糊);次按钮用透明底配荧光绿描边;分隔线用 3px solid #0c0a14 的粗线。禁止:任何圆角、任何渐变色、模糊柔和投影、细字重、衬线字体、抗锯齿式的柔和边缘。",
    promptEn:
      'Design this page in Pixel Art style: base the page on midnight blue #26233a; cards fill with dark grey-violet #1f1d2e and a chunky 3px solid #0c0a14 square border — every radius is 0; swap the body font for a monospace stack \'"Courier New", ui-monospace, monospace\' to sell the game-sprite feel; the accent color is glowing green #7fff6b; headings are fully uppercase, weight 700, tracked to 0.04em; badges are glowing green fills with pure black text in sharp rectangles, no border; the primary button is glowing green on black text with a hard shadow box-shadow: 4px 4px 0 0 #0c0a14 (zero blur); the secondary button is transparent with a glowing green outline; dividers are thick 3px solid #0c0a14 rules. Forbidden: any rounded corners, any gradients, soft blurred shadows, thin font weights, serif fonts, anti-aliased soft edges.',
    recipeZh: [
      "底色深夜蓝 #26233a;卡片 #1f1d2e + 3px solid #0c0a14,圆角全部为 0",
      '全局等宽字体 \'"Courier New", ui-monospace, monospace\'',
      "强调色荧光绿 #7fff6b;标题 uppercase、字重 700、字间距 0.04em",
      "主按钮绿底黑字 + 硬阴影 4px 4px 0 0 #0c0a14(零模糊),次按钮透明绿框",
      "分隔线加粗到 3px solid #0c0a14,拒绝任何渐变与模糊阴影",
    ],
    recipe: [
      "Base midnight blue #26233a; cards #1f1d2e with 3px solid #0c0a14, all radii at 0",
      'Global monospace stack \'"Courier New", ui-monospace, monospace\'',
      "Accent glowing green #7fff6b; headings uppercase, weight 700, tracking 0.04em",
      "Primary button green on black with hard shadow 4px 4px 0 0 #0c0a14 (zero blur); secondary is transparent with a green outline",
      "Thick 3px solid #0c0a14 dividers; no gradients or soft shadows anywhere",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#26233a",
        "--st-page-fg": "#e8e6f0",
        "--st-muted": "#a8a4c0",
        "--st-card-bg": "#1f1d2e",
        "--st-card-border": "3px solid #0c0a14",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "6px 6px 0 0 #0c0a14",
        "--st-divider": "3px solid #0c0a14",
        "--st-accent": "#7fff6b",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0.04em",
        "--st-heading-transform": "uppercase",
        "--st-font": '"Courier New", ui-monospace, monospace',
        "--st-badge-bg": "#7fff6b",
        "--st-badge-fg": "#0c0a14",
        "--st-badge-border": "none",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.04em",
        "--st-btn-primary-bg": "#7fff6b",
        "--st-btn-primary-fg": "#0c0a14",
        "--st-btn-primary-border": "3px solid #0c0a14",
        "--st-btn-primary-shadow": "4px 4px 0 0 #0c0a14",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#7fff6b",
        "--st-btn-secondary-border": "3px solid #7fff6b",
      },
    },
  },
  {
    slug: "frutiger-aero",
    name: "Frutiger Aero",
    nameZh: "Frutiger Aero",
    group: "retro",
    aliases: ["Frutiger Aero", "Vista 风", "水晶气泡风", "Aero 玻璃风"],
    description:
      "Sky-blue-to-grass gradients, dewy glass cards and a grass-green glow — 2000s optimism rendered in Aero glass.",
    descriptionZh: "天空到草地的渐变配露珠玻璃卡片,草绿微光点缀,是 2000 年代那股乐观的 Aero 玻璃质感。",
    bestFor: "Eco/wellness product pages, early-2000s tech nostalgia campaigns, weather/utility apps, clean-tech brand sites",
    bestForZh: "环保/健康类产品页、2000s 科技怀旧campaign、天气/工具类应用、清洁科技品牌站",
    promptZh:
      "请用 Frutiger Aero 风格设计这个页面:整页底色用清透渐变 linear-gradient(160deg, #9fd8f7 0%, #e8f7ff 55%, #d3f0e2 100%),模拟天空到草地的自然光感;卡片用半透明白 rgba(255,255,255,.6) 叠 8px 高斯模糊(backdrop-filter: blur(8px)),配 1px solid rgba(255,255,255,.9) 的高光描边,营造玻璃水珠质感;大卡片圆角 16px,按钮 / 徽标用 999px 胶囊圆角;强调色用草绿 #58b947;主按钮绿底白字,配自然光泽投影 0 4px 12px rgba(88,185,71,.45);次按钮用白 70% 底深蓝字;正文字色深蓝绿 #17435f,次要文字用 rgba(23,67,95,.65);背景叠加柔光层增强清透气泡感。禁止:暗色调背景、粗黑描边、硬直角阴影、故障噪点或做旧滤镜、低饱和灰调。",
    promptEn:
      "Design this page in Frutiger Aero style: base the page on a fresh sky-to-grass gradient linear-gradient(160deg, #9fd8f7 0%, #e8f7ff 55%, #d3f0e2 100%); cards sit on translucent white rgba(255,255,255,.6) with an 8px backdrop blur (backdrop-filter: blur(8px)) and a glossy highlight edge 1px solid rgba(255,255,255,.9), for a dewy glass-bubble feel; large cards use 16px rounded corners while buttons and badges go full capsule at 999px; the accent color is grass green #58b947; the primary button is green on white text with a natural gloss shadow 0 4px 12px rgba(88,185,71,.45); the secondary button is 70% white on deep-blue text; body copy sits at deep teal-blue #17435f, secondary text at rgba(23,67,95,.65); layer a soft glow to reinforce the crisp bubbly optimism. Forbidden: dark backgrounds, thick black outlines, hard sharp-cornered shadows, glitch noise or aged/grunge filters, desaturated grey tones.",
    recipeZh: [
      "底色天空到草地渐变 linear-gradient(160deg, #9fd8f7, #e8f7ff, #d3f0e2)",
      "卡片 rgba(255,255,255,.6) + backdrop-filter: blur(8px) + 1px solid rgba(255,255,255,.9) 高光边",
      "大圆角 16px(卡片)+ 999px 胶囊(按钮/徽标)",
      "强调色草绿 #58b947;主按钮绿底白字 + 自然光泽阴影 0 4px 12px rgba(88,185,71,.45)",
      "次按钮白 70% 底深蓝字;叠加柔光层增强清透气泡感",
    ],
    recipe: [
      "Sky-to-grass gradient linear-gradient(160deg, #9fd8f7, #e8f7ff, #d3f0e2)",
      "Cards use rgba(255,255,255,.6) with backdrop-filter: blur(8px) and a glossy 1px solid rgba(255,255,255,.9) edge",
      "Large 16px radius on cards, full 999px capsule on buttons/badges",
      "Accent grass green #58b947; primary button green on white with natural gloss shadow 0 4px 12px rgba(88,185,71,.45)",
      "Secondary button 70% white on deep-blue text; layer a soft glow for the crisp bubbly finish",
    ],
    skin: {
      backdrop: "aurora",
      vars: {
        "--st-page-bg": "linear-gradient(160deg, #9fd8f7 0%, #e8f7ff 55%, #d3f0e2 100%)",
        "--st-page-fg": "#17435f",
        "--st-muted": "rgba(23,67,95,.65)",
        "--st-card-bg": "rgba(255,255,255,.6)",
        "--st-card-border": "1px solid rgba(255,255,255,.9)",
        "--st-card-blur": "blur(8px)",
        "--st-radius-lg": "16px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 8px 20px rgba(23,67,95,.15)",
        "--st-divider": "1px solid rgba(255,255,255,.8)",
        "--st-accent": "#58b947",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "rgba(255,255,255,.7)",
        "--st-badge-fg": "#17435f",
        "--st-badge-border": "1px solid rgba(255,255,255,.9)",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#58b947",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow": "0 4px 12px rgba(88,185,71,.45)",
        "--st-btn-secondary-bg": "rgba(255,255,255,.7)",
        "--st-btn-secondary-fg": "#17435f",
        "--st-btn-secondary-border": "1px solid rgba(255,255,255,.9)",
      },
    },
  },
];
