import type { StyleEntry } from "./types";

// 复古经典谱系:20 世纪设计运动的原样复刻,而非泛泛的"怀旧"。

export const retroClassicStyles: StyleEntry[] = [
  {
    slug: "memphis",
    name: "Memphis",
    nameZh: "孟菲斯",
    group: "retro",
    aliases: ["孟菲斯设计", "Memphis Design", "80s 波普几何", "Postmodern Memphis"],
    description:
      "80s Italian toy-shop energy — primary-color geometry, hard candy shadows and a radius clash between rounded cards and pill buttons.",
    descriptionZh: "80 年代意大利玩具铺的欢闹感,原色几何图形、糖果硬阴影,卡片圆角和胶囊按钮故意打架。",
    bestFor: "Kids' product landing pages, playful SaaS onboarding, creative studio portfolios, festival microsites",
    bestForZh: "儿童产品落地页、活泼调性的 SaaS 引导页、创意工作室作品集、活动/音乐节微站",
    promptZh:
      "请用孟菲斯(Memphis)风格设计这个页面:底色用奶白 #fff8e7;卡片用纯白 #ffffff 配 2px 纯黑描边(#14140f),外加一圈撞色硬阴影(box-shadow: 5px 5px 0 0 #ff4d6d,零模糊);点缀亮黄 #ffce00 作为强调色,用在图形装饰、下划线、圆点上;卡片圆角适中(12px),但按钮做成胶囊形(999px),两种圆角混搭出玩具感;主按钮用亮蓝 #2f6bff 底 + 白字 + 2px 黑框,次按钮白底黑框;标题字重 800,配几何小图形(三角、锯齿、波浪线)做装饰;分隔线用 2px 纯黑实线。禁止:柔和渐变、单色极简、玻璃拟态模糊、纤细线条、任何金属质感、大面积留白的克制排版。",
    promptEn:
      "Design this page in Memphis style: a warm cream background (#fff8e7); cards in pure white (#ffffff) with a 2px solid black (#14140f) border plus a candy-colored hard shadow (box-shadow: 5px 5px 0 0 #ff4d6d, zero blur); sprinkle bright yellow (#ffce00) accents on squiggles, underlines and dots; cards keep a moderate 12px radius while buttons turn fully pill-shaped (999px) — the radius clash is what reads as toy-like; primary buttons are bright blue (#2f6bff) with white text and a 2px black border, secondary buttons are white with a black border; headings are weight 800 with small geometric doodles (triangles, zigzags, squiggles) scattered around; dividers are 2px solid black. Forbidden: soft gradients, monochrome minimalism, glassmorphism blur, thin hairlines, any metallic sheen, restrained whitespace-heavy layouts.",
    recipeZh: [
      "底 #fff8e7 + 卡片纯白 #ffffff,2px 纯黑描边 #14140f",
      "撞色硬阴影 box-shadow: 5px 5px 0 0 #ff4d6d,零模糊",
      "圆角混搭:卡片 12px、按钮胶囊 999px,制造玩具感落差",
      "accent 亮黄 #ffce00 用于徽标底色、装饰图形和下划线",
      "主按钮亮蓝 #2f6bff 白字 + 黑框;次按钮白底黑框,呼应粗野轮廓",
    ],
    recipe: [
      "Base #fff8e7 with pure-white cards #ffffff, 2px solid black border #14140f",
      "Clashing hard shadow: box-shadow: 5px 5px 0 0 #ff4d6d, zero blur",
      "Radius clash: 12px cards vs. 999px pill buttons for the toy-shop tension",
      "Accent bright yellow #ffce00 for badge fills, doodles and underlines",
      "Primary buttons bright blue #2f6bff on white text with a black border; secondary buttons white with a black border",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#fff8e7",
        "--st-page-fg": "#14140f",
        "--st-muted": "#4a4a40",
        "--st-card-bg": "#ffffff",
        "--st-card-border": "2px solid #14140f",
        "--st-card-blur": "none",
        "--st-radius-lg": "12px",
        "--st-radius-sm": "999px",
        "--st-shadow": "5px 5px 0 0 #ff4d6d",
        "--st-divider": "2px solid #14140f",
        "--st-accent": "#ffce00",
        "--st-heading-weight": "800",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "#ffce00",
        "--st-badge-fg": "#14140f",
        "--st-badge-border": "2px solid #14140f",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.06em",
        "--st-btn-primary-bg": "#2f6bff",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "2px solid #14140f",
        "--st-btn-primary-shadow": "4px 4px 0 0 #14140f",
        "--st-btn-secondary-bg": "#ffffff",
        "--st-btn-secondary-fg": "#14140f",
        "--st-btn-secondary-border": "2px solid #14140f",
      },
    },
  },
  {
    slug: "bauhaus",
    name: "Bauhaus",
    nameZh: "包豪斯",
    group: "retro",
    aliases: ["包豪斯设计", "Bauhaus Design", "几何构成主义", "三原色构成风"],
    description:
      "Primary-color-and-black geometric composition — square corners, zero ornament, the functionalist restraint of the 1920s design school.",
    descriptionZh: "三原色加黑白的几何构成,直角、无装饰,复刻 1920 年代设计学院的功能主义克制感。",
    bestFor: "Design school portfolios, architecture/product studio sites, gallery exhibition microsites, editorial design showcases",
    bestForZh: "设计院校作品集、建筑/工业设计工作室主页、美术馆展览微站、编辑设计类作品展示页",
    promptZh:
      "请用包豪斯(Bauhaus)风格设计这个页面:底色米白 #f4efe6;卡片同为米白,配 2px 纯黑描边 #17171b,直角无圆角(border-radius: 0);完全不用阴影(box-shadow: none);强调色用纯正红 #d9291a,只在关键色块和链接上使用;徽标用黄底 #f0a500 黑字直角矩形;主按钮深蓝 #1f4796 底白字直角,次按钮透明底黑框;标题字重 800、字间距为 0(tracking: 0),用无衬线字体保持功能主义的克制;分隔线 2px 纯黑实线,版式按网格对齐、用圆/三角/矩形等几何色块做点缀。禁止:圆角、渐变、阴影、柔和粉彩色、衬线花体字、任何装饰性纹理。",
    promptEn:
      "Design this page in Bauhaus style: a warm off-white background (#f4efe6); cards in the same off-white with a 2px solid black border (#17171b), fully square corners (border-radius: 0); no shadows at all (box-shadow: none); the accent is a pure primary red (#d9291a), used sparingly on key blocks and links; badges are a yellow (#f0a500) block with black text and square corners; primary buttons are deep blue (#1f4796) with white text and square corners, secondary buttons are transparent with a black border; headings are weight 800 with zero letter-spacing (tracking: 0), set in a sans-serif to keep the functionalist restraint; dividers are 2px solid black, and the layout aligns to a strict grid with flat geometric shapes (circles, triangles, rectangles) as color-block decoration. Forbidden: rounded corners, gradients, shadows, soft pastel colors, decorative serif scripts, any ornamental texture.",
    recipeZh: [
      "底/卡片同色米白 #f4efe6,2px 纯黑描边 #17171b,border-radius: 0",
      "三原色克制使用:红 #d9291a 做 accent,黄 #f0a500 做徽标底",
      "box-shadow 全局关闭,靠描边和色块建立层次",
      "标题字重 800、letter-spacing 为 0,无衬线字体",
      "网格对齐版式 + 圆/三角/矩形纯色几何图形做点缀",
    ],
    recipe: [
      "Base and cards share off-white #f4efe6, 2px solid black border #17171b, border-radius: 0",
      "Primary colors used sparingly: red #d9291a as accent, yellow #f0a500 for badges",
      "box-shadow disabled everywhere — hierarchy comes from borders and color blocks",
      "Headings weight 800 with zero letter-spacing, sans-serif only",
      "Grid-aligned layout with flat geometric shapes (circles, triangles, rectangles) as accents",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#f4efe6",
        "--st-page-fg": "#17171b",
        "--st-muted": "#5c5c60",
        "--st-card-bg": "#f4efe6",
        "--st-card-border": "2px solid #17171b",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "none",
        "--st-divider": "2px solid #17171b",
        "--st-accent": "#d9291a",
        "--st-heading-weight": "800",
        "--st-heading-tracking": "0em",
        "--st-badge-bg": "#f0a500",
        "--st-badge-fg": "#17171b",
        "--st-badge-border": "2px solid #17171b",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.04em",
        "--st-btn-primary-bg": "#1f4796",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "2px solid #17171b",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#17171b",
        "--st-btn-secondary-border": "2px solid #17171b",
      },
    },
  },
  {
    slug: "art-deco",
    name: "Art Deco",
    nameZh: "装饰艺术",
    group: "retro",
    aliases: ["装饰艺术风", "Art Deco", "盖茨比风", "黑金风"],
    description:
      "Black-and-gold symmetrical luxury with hairline gold linework, reviving the ceremonial glamour of the 1920s Jazz Age.",
    descriptionZh: "黑金配色的奢华对称感,金色细线勾边,复刻 1920 年代爵士乐时代的仪式感光泽。",
    bestFor: "Luxury hospitality/hotel sites, high-end event invitations, jewelry and fashion boutiques, premium membership clubs",
    bestForZh: "高端酒店/会所官网、奢侈品活动邀请页、珠宝服饰精品店、付费会员俱乐部落地页",
    promptZh:
      "请用装饰艺术(Art Deco)风格设计这个页面:底色用近黑的墨绿 #0f1713;正文用米金白 #ece5d3,弱化文字用 rgba(232,222,196,.6);强调色用香槟金 #c8a24b;卡片背景几乎透明 rgba(200,162,75,.04),配 1px 细金框 rgba(200,162,75,.55),直角无圆角;标题用衬线字体(Georgia / Times New Roman),全大写、字间距拉宽到 0.1em、字重 700,体现装饰艺术的对称仪式感;徽标透明底、金色描边、金字全大写、字间距 0.18em;主按钮金底黑字直角,次按钮透明金框;分隔线用 1px 细金线;完全不用阴影。禁止:圆角、粗描边、亮色荧光色、无衬线随意字体、任何卡通化插画。",
    promptEn:
      "Design this page in Art Deco style: a near-black deep green background (#0f1713); body text in a warm gold-white (#ece5d3), muted text at rgba(232,222,196,.6); the accent is a champagne gold (#c8a24b); cards sit on a near-transparent gold wash (rgba(200,162,75,.04)) with a hairline 1px gold border (rgba(200,162,75,.55)) and square corners; headings use a serif face (Georgia / Times New Roman), set in uppercase with wide 0.1em tracking and weight 700 to read as symmetrical and ceremonial; badges are transparent with a gold border and uppercase gold text at 0.18em tracking; primary buttons are gold-filled with black text and square corners, secondary buttons are transparent with a gold border; dividers are hairline 1px gold lines; shadows are disabled entirely. Forbidden: rounded corners, thick borders, neon or bright saturated colors, casual sans-serif headings, any cartoonish illustration.",
    recipeZh: [
      "底墨绿 #0f1713 + 文字米金白 #ece5d3,营造黑金奢华对比",
      "卡片近透明金色底 rgba(200,162,75,.04) + 1px 细金框,直角无圆角",
      "标题用衬线字体、全大写、tracking 0.1em、字重 700",
      "accent 香槟金 #c8a24b 贯穿徽标、按钮和分隔线的细线勾勒",
      "阴影全部关闭,靠金线和留白建立层次感",
    ],
    recipe: [
      "Deep green base #0f1713 with gold-white text #ece5d3 for the black-and-gold contrast",
      "Cards use a near-transparent gold wash rgba(200,162,75,.04) with a hairline 1px gold border, square corners",
      "Headings in a serif face, uppercase, 0.1em tracking, weight 700",
      "Champagne gold accent #c8a24b threads through badges, buttons and hairline dividers",
      "Shadows disabled entirely — hierarchy comes from gold linework and negative space",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "#0f1713",
        "--st-page-fg": "#ece5d3",
        "--st-muted": "rgba(232,222,196,.6)",
        "--st-card-bg": "rgba(200,162,75,.04)",
        "--st-card-border": "1px solid rgba(200,162,75,.55)",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "none",
        "--st-divider": "1px solid rgba(200,162,75,.45)",
        "--st-accent": "#c8a24b",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0.1em",
        "--st-heading-font": '"Georgia", "Times New Roman", serif',
        "--st-heading-transform": "uppercase",
        "--st-badge-bg": "transparent",
        "--st-badge-fg": "#c8a24b",
        "--st-badge-border": "1px solid #c8a24b",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.18em",
        "--st-btn-primary-bg": "#c8a24b",
        "--st-btn-primary-fg": "#0f1713",
        "--st-btn-primary-border": "1px solid #c8a24b",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#c8a24b",
        "--st-btn-secondary-border": "1px solid #c8a24b",
      },
    },
  },
  {
    slug: "retro-terminal",
    name: "Retro Terminal",
    nameZh: "复古终端",
    group: "retro",
    aliases: ["复古终端风", "CRT Terminal", "黑客帝国风", "DOS 风"],
    description:
      "Glowing green phosphor text on a black CRT screen with flickering scanlines — a terminal window straight out of the Matrix.",
    descriptionZh: "黑色 CRT 屏幕上的荧光绿字符,叠加闪烁扫描线,像是黑客帝国里跳出来的终端窗口。",
    bestFor: "Developer tool landing pages, hacker-themed games, cybersecurity product sites, retro tech portfolio pages",
    bestForZh: "开发者工具官网、黑客主题游戏、网络安全产品站、复古科技主题作品集",
    promptZh:
      "请用复古终端(Retro Terminal)风格设计这个页面:底色纯黑偏绿 #050c06,叠加扫描线纹理(scanlines);全局字体用等宽字体(Courier New / ui-monospace);正文荧光绿 #c7ffd4,弱化文字用 rgba(120,255,150,.55);强调色用高亮荧光绿 #33ff66;卡片背景几乎透明的绿色 rgba(51,255,102,.05),配 1px 细绿框 rgba(51,255,102,.4),直角无圆角;卡片和按钮都带荧光辉光阴影(box-shadow: 0 0 16px rgba(51,255,102,.18));标题全大写、字间距 0.06em、字重 700;徽标绿底黑字全大写。禁止:衬线字体、圆角、暖色调、渐变背景、任何拟物质感贴图。",
    promptEn:
      "Design this page in Retro Terminal style: a near-black green-tinted background (#050c06) overlaid with a scanline texture; the whole UI uses a monospace font (Courier New / ui-monospace); body text is phosphor green (#c7ffd4), muted text at rgba(120,255,150,.55); the accent is a bright glowing green (#33ff66); cards sit on a near-transparent green wash (rgba(51,255,102,.05)) with a hairline 1px green border (rgba(51,255,102,.4)) and square corners; cards and buttons both carry a phosphor glow shadow (box-shadow: 0 0 16px rgba(51,255,102,.18)); headings are uppercase with 0.06em tracking and weight 700; badges are green-filled with black uppercase text. Forbidden: serif fonts, rounded corners, warm color tones, gradient backgrounds, any skeuomorphic texture.",
    recipeZh: [
      "底 #050c06 叠加 scanlines 背景,营造 CRT 屏幕感",
      "全局等宽字体 Courier New / ui-monospace,荧光绿文字 #c7ffd4",
      "卡片近透明绿底 rgba(51,255,102,.05) + 1px 细绿框,直角无圆角",
      "卡片/按钮用荧光辉光阴影 box-shadow: 0 0 16px rgba(51,255,102,.18)",
      "标题全大写、tracking 0.06em、字重 700,徽标绿底黑字",
    ],
    recipe: [
      "Base #050c06 with a scanline overlay to sell the CRT feel",
      "Monospace font throughout (Courier New / ui-monospace), phosphor green text #c7ffd4",
      "Cards on a near-transparent green wash rgba(51,255,102,.05) with a hairline 1px green border, square corners",
      "Cards and buttons carry a phosphor glow: box-shadow: 0 0 16px rgba(51,255,102,.18)",
      "Headings uppercase, 0.06em tracking, weight 700; badges are green-filled with black text",
    ],
    skin: {
      backdrop: "scanlines",
      vars: {
        "--st-page-bg": "#050c06",
        "--st-page-fg": "#c7ffd4",
        "--st-muted": "rgba(120,255,150,.55)",
        "--st-card-bg": "rgba(51,255,102,.05)",
        "--st-card-border": "1px solid rgba(51,255,102,.4)",
        "--st-card-blur": "none",
        "--st-radius-lg": "0px",
        "--st-radius-sm": "0px",
        "--st-shadow": "0 0 16px rgba(51,255,102,.18)",
        "--st-divider": "1px solid rgba(51,255,102,.35)",
        "--st-accent": "#33ff66",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0.06em",
        "--st-heading-transform": "uppercase",
        "--st-font": '"Courier New", ui-monospace, monospace',
        "--st-badge-bg": "#33ff66",
        "--st-badge-fg": "#050c06",
        "--st-badge-border": "none",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.05em",
        "--st-btn-primary-bg": "#33ff66",
        "--st-btn-primary-fg": "#050c06",
        "--st-btn-primary-border": "none",
        "--st-btn-primary-shadow": "0 0 12px rgba(51,255,102,.35)",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#33ff66",
        "--st-btn-secondary-border": "1px solid #33ff66",
      },
    },
  },
];
