import type { StyleEntry } from "./types";

// 科技未来谱系:数字原生界面 —— 从克制的暗色 SaaS 到张扬的赛博霓虹。

export const techStyles: StyleEntry[] = [
  {
    slug: "dark-tech",
    name: "Dark Tech",
    nameZh: "暗黑科技风",
    group: "tech",
    aliases: ["Linear 风", "Dark SaaS", "暗黑科技风", "暗色 SaaS 风"],
    description:
      "A restrained dark SaaS surface with soft glass cards and a single electric-violet accent — precise, quiet, unmistakably Linear-style.",
    descriptionZh: "克制的暗色 SaaS 界面,毛玻璃卡片配一抹电紫蓝强调色,精致到近乎沉默,一眼就是 Linear 风。",
    bestFor: "Dev tool / SaaS 官网,产品仪表盘,B2B 定价页,开发者文档首页",
    bestForZh: "开发者工具 / SaaS 官网、产品仪表盘、B2B 定价页、开发者文档首页",
    promptZh:
      "请用暗黑科技风(Dark Tech,Linear-style)风格设计这个页面:背景用竖向深色渐变 linear-gradient(180deg, #0d0e13 0%, #0a0b0f 100%);卡片用 rgba(255,255,255,.04) 底 + 1px solid rgba(255,255,255,.08) 描边,大圆角 10px;强调色是电紫蓝 #5e6ad2,只用在按钮、链接和少量高亮上;正文 #e6e7ec,次要文字用 55% 透明度;标题字重 600、字距 -0.02em,克制不张扬;主按钮紫蓝底白字,次按钮透明底 + 1px 细描边;卡片阴影极软 0 12px 32px rgba(0,0,0,.45)。禁止:高饱和撞色、粗黑描边、渐变强调色、圆角小于 8px、任何拟物质感、多种强调色混用。",
    promptEn:
      "Design this page in a Linear-style dark tech aesthetic: a vertical dark gradient background linear-gradient(180deg, #0d0e13 0%, #0a0b0f 100%); cards use rgba(255,255,255,.04) fill with a 1px solid rgba(255,255,255,.08) border and a generous 10px radius; a single electric-violet accent #5e6ad2 reserved for buttons, links and sparse highlights; body text #e6e7ec, muted text at 55% opacity; headings at weight 600 with -0.02em tracking, restrained and quiet; primary buttons are violet-filled with white text, secondary buttons are transparent with a thin 1px border; shadows are very soft, 0 12px 32px rgba(0,0,0,.45). Forbidden: saturated color clashes, thick black borders, gradient accent fills, radii under 8px, skeuomorphic textures, mixing more than one accent hue.",
    recipeZh: [
      "背景竖向深色渐变,而非纯黑,层次感来自明度差而非色相",
      "卡片 rgba(255,255,255,.04) + 1px 细描边,近似毛玻璃但不做模糊",
      "全站只留一个强调色(电紫蓝),按钮 / 链接 / 高亮统一复用",
      "标题字重 600、负字距 -0.02em,克制而不是加粗炫技",
      "分割线、按钮描边统一用低透明度白色,保持层级但不抢戏",
    ],
    recipe: [
      "Vertical dark gradient background, not flat black — depth comes from lightness, not hue",
      "Cards: rgba(255,255,255,.04) fill + 1px hairline border, glass-like without actual blur",
      "One accent color site-wide (electric violet), reused across buttons, links, highlights",
      "Headings at weight 600 with -0.02em tracking — restraint over boldness",
      "Dividers and secondary borders share the same low-opacity white for consistent hierarchy",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg": "linear-gradient(180deg, #0d0e13 0%, #0a0b0f 100%)",
        "--st-page-fg": "#e6e7ec",
        "--st-muted": "rgba(230,231,236,.55)",
        "--st-card-bg": "rgba(255,255,255,.04)",
        "--st-card-border": "1px solid rgba(255,255,255,.08)",
        "--st-card-blur": "none",
        "--st-radius-lg": "10px",
        "--st-radius-sm": "8px",
        "--st-shadow": "0 12px 32px rgba(0,0,0,.45)",
        "--st-divider": "1px solid rgba(255,255,255,.08)",
        "--st-accent": "#5e6ad2",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.02em",
        "--st-badge-bg": "rgba(94,106,210,.12)",
        "--st-badge-fg": "#a5adf0",
        "--st-badge-border": "1px solid rgba(94,106,210,.2)",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#5e6ad2",
        "--st-btn-primary-fg": "#ffffff",
        "--st-btn-primary-border": "1px solid #5e6ad2",
        "--st-btn-primary-shadow": "none",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#e6e7ec",
        "--st-btn-secondary-border": "1px solid rgba(255,255,255,.12)",
      },
    },
  },
  {
    slug: "cyberpunk",
    name: "Cyberpunk",
    nameZh: "赛博朋克风",
    group: "tech",
    aliases: ["赛博朋克", "Cyberpunk", "夜之城风", "霓虹科幻"],
    description:
      "Neon cyan and magenta slicing through a near-black grid — sharp corners, glowing edges, a night-city interface with an attitude.",
    descriptionZh: "电青与品红霓虹划破近黑背景网格,直角锐边、发光描边,一副夜之城界面的张扬姿态。",
    bestFor: "游戏 / 电竞官网,虚拟演唱会 / 元宇宙活动页,潮流数字藏品站,酷炫作品集主页",
    bestForZh: "游戏 / 电竞官网、虚拟演唱会 / 元宇宙活动页、潮流数字藏品站、酷炫作品集主页",
    promptZh:
      "请用赛博朋克(Cyberpunk)风格设计这个页面:背景近黑 #07070f,叠加一层低对比度网格线做深度;强调色是电青 #00f0ff,发光描边和文字投影都用它;徽章用品红 #ff2ea6 底 + 黑字 + 直角;卡片用 rgba(0,240,255,.04) 底 + 1px solid rgba(0,240,255,.35) 青色细描边,圆角极小 2px 几乎是直角;标题全大写、字距拉宽 0.04em、字重 700;主按钮青底黑字直角,次按钮透明底 + 青色描边;阴影用发光效果 0 0 20px rgba(0,240,255,.2) 而不是常规投影。禁止:大圆角、柔和阴影、粉彩低饱和配色、衬线字体、任何拟物纹理、圆润按钮。",
    promptEn:
      "Design this page in a cyberpunk style: a near-black background #07070f with a faint grid overlay for depth; the accent is electric cyan #00f0ff, used for glowing borders and text; badges are magenta #ff2ea6 fill with black text and sharp corners; cards use rgba(0,240,255,.04) fill with a 1px solid rgba(0,240,255,.35) cyan hairline border and near-zero 2px radius; headings are uppercase, tracked wide at 0.04em, weight 700; primary buttons are cyan-filled with black text and sharp corners, secondary buttons are transparent with a cyan outline; shadows are glows, 0 0 20px rgba(0,240,255,.2), never a conventional drop shadow. Forbidden: large border radii, soft diffuse shadows, pastel or desaturated palettes, serif typefaces, skeuomorphic textures, rounded pill buttons.",
    recipeZh: [
      "近黑底 + 低对比网格背景,营造夜间数据界面的纵深",
      "双色系统:青做主强调,品红只用于徽章 / 警示等次要强调",
      "圆角压到 2px 甚至直角,和圆润设计彻底划清界限",
      "标题大写 + 宽字距 + 粗字重,模拟电子屏幕的机械感",
      "阴影一律换成发光(box-shadow 无位移、大扩散、低不透明度)",
    ],
    recipe: [
      "Near-black base with a low-contrast grid overlay for night-city depth",
      "Two-color system: cyan for the primary accent, magenta reserved for badges/alerts",
      "Radii pushed to 2px or square — a hard break from rounded design",
      "Headings uppercase, wide-tracked, bold — mimics a digital readout",
      "Shadows are always glows (zero offset, large spread, low opacity), never conventional drop shadows",
    ],
    skin: {
      backdrop: "grid",
      layout: "default",
      vars: {
        "--st-page-bg": "#07070f",
        "--st-page-fg": "#d6faff",
        "--st-muted": "rgba(214,250,255,.55)",
        "--st-card-bg": "rgba(0,240,255,.04)",
        "--st-card-border": "1px solid rgba(0,240,255,.35)",
        "--st-card-blur": "none",
        "--st-radius-lg": "2px",
        "--st-radius-sm": "2px",
        "--st-shadow": "0 0 20px rgba(0,240,255,.2)",
        "--st-divider": "1px solid rgba(0,240,255,.3)",
        "--st-accent": "#00f0ff",
        "--st-heading-weight": "700",
        "--st-heading-tracking": "0.04em",
        "--st-heading-transform": "uppercase",
        "--st-badge-bg": "#ff2ea6",
        "--st-badge-fg": "#07070f",
        "--st-badge-border": "1px solid #ff2ea6",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.08em",
        "--st-btn-primary-bg": "#00f0ff",
        "--st-btn-primary-fg": "#07070f",
        "--st-btn-primary-border": "1px solid #00f0ff",
        "--st-btn-primary-shadow": "0 0 16px rgba(0,240,255,.35)",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#00f0ff",
        "--st-btn-secondary-border": "1px solid rgba(0,240,255,.5)",
      },
    },
  },
  {
    slug: "aurora",
    name: "Aurora Gradient",
    nameZh: "极光渐变风",
    group: "tech",
    aliases: ["极光渐变", "Aurora Gradient", "Mesh Gradient", "弥散光风"],
    description:
      "Diffuse multi-hue gradient light pooling behind frosted glass cards — soft, borderless, like an aurora seen through a window.",
    descriptionZh: "多色弥散光在毛玻璃卡片背后流动堆叠,柔和无边界,像隔着窗户看极光。",
    bestFor: "AI 产品官网,创意工具 Landing Page,音乐 / 潮流品牌活动页,融资 / 发布会宣传页",
    bestForZh: "AI 产品官网、创意工具 Landing Page、音乐 / 潮流品牌活动页、融资 / 发布会宣传页",
    promptZh:
      "请用极光渐变(Aurora Gradient)风格设计这个页面:背景由多层径向渐变叠加而成 —— 左上蓝紫、右上青绿、右下紫粉,底色深蓝 #0b1026,渐变边缘柔和过渡到透明,营造弥散光感;卡片用 rgba(255,255,255,.06) 底 + 1px solid rgba(255,255,255,.12) 描边 + backdrop-filter: blur(10px) 毛玻璃效果,大圆角 20px;强调色青绿 #22d3ee;正文 #f1f5fd,次要文字 65% 透明度;徽章用半透明白底胶囊形;主按钮白底深蓝字胶囊形,次按钮透明底 + 白色细描边;阴影柔和 0 8px 32px rgba(4,10,30,.4)。禁止:纯色平面背景、硬边框、直角、高饱和撞色、深色卡片、任何网格或扫描线装饰。",
    promptEn:
      "Design this page in an aurora gradient style: a background built from stacked radial gradients — blue-violet top-left, cyan-teal top-right, purple-pink bottom-right, over a deep navy base #0b1026, each gradient fading softly to transparent for a diffuse-light feel; cards use rgba(255,255,255,.06) fill with a 1px solid rgba(255,255,255,.12) border and backdrop-filter: blur(10px) for frosted glass, with a generous 20px radius; the accent is cyan-teal #22d3ee; body text #f1f5fd, muted text at 65% opacity; badges are translucent white pills; primary buttons are white-filled with deep-navy text in pill shape, secondary buttons are transparent with a thin white outline; shadows are soft, 0 8px 32px rgba(4,10,30,.4). Forbidden: flat solid-color backgrounds, hard borders, sharp corners, saturated color clashes, dark opaque cards, any grid or scanline decoration.",
    recipeZh: [
      "背景是唯一的舞台:多个 radial-gradient 叠加 + 深蓝底色,不需要额外装饰层",
      "卡片必须半透明 + blur,让底层渐变光透出来,才是「极光」的核心",
      "大圆角(20px)+ 胶囊按钮,呼应背景的流动柔和感",
      "强调色只挑一个饱和青绿,避免和背景渐变的多色抢戏",
      "阴影/描边全部走低透明度白色,不用纯黑,保持轻盈通透",
    ],
    recipe: [
      "The background is the star: layered radial-gradients over a deep navy base, no extra decorative layer needed",
      "Cards must be translucent + blurred so the gradient glow shows through — that's the core of 'aurora'",
      "Large radii (20px) and pill buttons echo the background's soft, flowing feel",
      "Pick one saturated cyan-teal accent so it doesn't compete with the multi-hue background",
      "Shadows and borders stay low-opacity white, never pure black, to keep it light and translucent",
    ],
    skin: {
      backdrop: "none",
      vars: {
        "--st-page-bg":
          "radial-gradient(60% 80% at 20% 10%, rgba(64,93,230,.55), transparent 60%), radial-gradient(50% 70% at 80% 20%, rgba(45,212,191,.4), transparent 60%), radial-gradient(70% 90% at 60% 90%, rgba(168,85,247,.45), transparent 65%), #0b1026",
        "--st-page-fg": "#f1f5fd",
        "--st-muted": "rgba(241,245,253,.65)",
        "--st-card-bg": "rgba(255,255,255,.06)",
        "--st-card-border": "1px solid rgba(255,255,255,.12)",
        "--st-card-blur": "blur(10px)",
        "--st-radius-lg": "20px",
        "--st-radius-sm": "999px",
        "--st-shadow": "0 8px 32px rgba(4,10,30,.4)",
        "--st-divider": "1px solid rgba(255,255,255,.14)",
        "--st-accent": "#22d3ee",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "-0.01em",
        "--st-badge-bg": "rgba(255,255,255,.1)",
        "--st-badge-fg": "#f1f5fd",
        "--st-badge-border": "1px solid rgba(255,255,255,.2)",
        "--st-badge-transform": "none",
        "--st-badge-tracking": "0.02em",
        "--st-btn-primary-bg": "#ffffff",
        "--st-btn-primary-fg": "#0b1026",
        "--st-btn-primary-border": "1px solid #ffffff",
        "--st-btn-primary-shadow": "0 4px 20px rgba(255,255,255,.2)",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#f1f5fd",
        "--st-btn-secondary-border": "1px solid rgba(255,255,255,.4)",
      },
    },
  },
  {
    slug: "sci-fi-hud",
    name: "Sci-Fi HUD",
    nameZh: "科幻 HUD 风",
    group: "tech",
    aliases: ["科幻 HUD", "FUI", "全息界面", "太空舱 UI"],
    description:
      "A cockpit-style heads-up display in monospace type and cyan hairlines — data-dense, diegetic, straight out of a spacecraft interface.",
    descriptionZh: "等宽字体配青色细线的驾驶舱式抬头显示界面,数据密集、拟真感强,像是从飞船座舱里搬出来的。",
    bestFor: "监控 / 数据大屏,航天 / 硬核科技产品页,极客工具面板,科幻主题活动 / 游戏 UI",
    bestForZh: "监控 / 数据大屏、航天 / 硬核科技产品页、极客工具面板、科幻主题活动 / 游戏 UI",
    promptZh:
      "请用科幻 HUD(Sci-Fi HUD)风格设计这个页面:背景深蓝黑 #04101c,叠加低对比网格线模拟舱体扫描面;全局字体用等宽字体 ui-monospace / SF Mono,强化数据仪表盘质感;强调色 HUD 青 #35e0ff;卡片用 rgba(53,224,255,.05) 底 + 1px solid rgba(53,224,255,.4) 青色细描边,圆角极小 2px;标题全大写、字距拉宽到 0.12em、字重 600,模拟仪表读数;徽章透明底 + 青色描边 + 青字,全大写字距 0.2em;主按钮青底深蓝黑字直角,次按钮透明底青色描边;阴影是发光而非投影 0 0 18px rgba(53,224,255,.15)。禁止:衬线或人文字体、大圆角、暖色调、柔和渐变、任何手绘 / 有机线条、比例失调的粗描边。",
    promptEn:
      "Design this page in a sci-fi HUD style: a deep navy-black background #04101c with a low-contrast grid overlay simulating a cockpit scan surface; use a monospace font stack (ui-monospace / SF Mono) throughout to reinforce the data-readout feel; the accent is HUD cyan #35e0ff; cards use rgba(53,224,255,.05) fill with a 1px solid rgba(53,224,255,.4) cyan hairline border and a near-zero 2px radius; headings are uppercase, tracked wide at 0.12em, weight 600, mimicking instrument readouts; badges are transparent with a cyan outline and cyan uppercase text tracked at 0.2em; primary buttons are cyan-filled with dark navy text and sharp corners, secondary buttons are transparent with a cyan outline; shadows are glows, not drop shadows, 0 0 18px rgba(53,224,255,.15). Forbidden: serif or humanist typefaces, large border radii, warm color tones, soft gradients, any hand-drawn or organic lines, oversized borders.",
    recipeZh: [
      "全局等宽字体是灵魂:标题、正文、徽章都用它,拒绝任何人文衬线",
      "低对比网格背景模拟舱体扫描面,不用高对比噪点或纹理",
      "圆角压到 2px,细描边(1px)取代粗框,保持精密仪表感",
      "标题 / 徽章统一大写 + 大字距,读数感来自字距而非字号",
      "阴影全部换成青色发光,呼应 HUD 屏幕的自发光特性",
    ],
    recipe: [
      "A monospace font everywhere is the soul of it — headings, body, badges — no humanist serifs",
      "Low-contrast grid background simulates a cockpit scan surface, not high-contrast noise or texture",
      "Radii pushed to 2px, hairline 1px borders instead of thick frames — keeps the precision-instrument feel",
      "Headings and badges are uppercase with wide tracking — the readout feel comes from tracking, not size",
      "Shadows are all cyan glows, echoing the self-illuminated nature of a HUD screen",
    ],
    skin: {
      backdrop: "grid",
      vars: {
        "--st-page-bg": "#04101c",
        "--st-page-fg": "#cfeefb",
        "--st-muted": "rgba(207,238,251,.5)",
        "--st-card-bg": "rgba(53,224,255,.05)",
        "--st-card-border": "1px solid rgba(53,224,255,.4)",
        "--st-card-blur": "none",
        "--st-radius-lg": "2px",
        "--st-radius-sm": "2px",
        "--st-shadow": "0 0 18px rgba(53,224,255,.15)",
        "--st-divider": "1px solid rgba(53,224,255,.3)",
        "--st-accent": "#35e0ff",
        "--st-heading-weight": "600",
        "--st-heading-tracking": "0.12em",
        "--st-heading-transform": "uppercase",
        "--st-font": 'ui-monospace, "SF Mono", monospace',
        "--st-badge-bg": "transparent",
        "--st-badge-fg": "#35e0ff",
        "--st-badge-border": "1px solid #35e0ff",
        "--st-badge-transform": "uppercase",
        "--st-badge-tracking": "0.2em",
        "--st-btn-primary-bg": "#35e0ff",
        "--st-btn-primary-fg": "#04101c",
        "--st-btn-primary-border": "1px solid #35e0ff",
        "--st-btn-primary-shadow": "0 0 14px rgba(53,224,255,.3)",
        "--st-btn-secondary-bg": "transparent",
        "--st-btn-secondary-fg": "#35e0ff",
        "--st-btn-secondary-border": "1px solid rgba(53,224,255,.5)",
      },
    },
  },
];
