// Everyday interface concepts. An entry may point at a component we already
// ship. It never invents an installable for a concept we do not have.

export const CONCEPT_GROUPS = [
  "actions",
  "writing",
  "choice",
  "navigation",
  "jargon",
  "overlay",
  "feedback",
  "content",
] as const;

export type ConceptGroup = (typeof CONCEPT_GROUPS)[number];

export type ConceptComponent = {
  category: "motion" | "blocks";
  slug: string;
  previewKey: string;
  installSlug: string;
};

export type ConceptEntry = {
  slug: string;
  group: ConceptGroup;
  name: string;
  nameZh: string;
  aliases: readonly string[];
  sentence: string;
  sentenceZh: string;
  prompt: string;
  promptZh: string;
  component?: ConceptComponent;
  /** One way we ship the idea. The sample on the page stays the plain concept. */
  related?: {
    category: "motion" | "blocks";
    slug: string;
    name: string;
    nameZh: string;
  };
};

export const CONCEPTS: readonly ConceptEntry[] = [
  {
    slug: "button",
    group: "actions",
    name: "Button",
    nameZh: "按钮",
    aliases: ["CTA", "主按钮", "call to action"],
    sentence: "A control a person presses to do one thing.",
    sentenceZh: "让人点一下就做一件事的控件。",
    prompt:
      "Install UI Lab button-base and import Button from it. Press feedback uses the spring in that component. Idle, loading, success, and error use StatefulButton from the same component. When it should follow the pointer, use MagneticButton.",
    promptZh:
      "安装 UI Lab 的 button-base，引入其中的 Button。按压用它自带的弹簧。空闲、加载中、成功、失败用同一个组件里的 StatefulButton。要跟着指针走，用 MagneticButton。",
    component: {
      category: "motion",
      slug: "button",
      previewKey: "motion/button-base",
      installSlug: "button-base",
    },
  },
  {
    slug: "icon-button",
    group: "actions",
    name: "Icon button",
    nameZh: "图标按钮",
    aliases: ["glyph button", "tool button"],
    sentence: "A button that shows an icon and no visible text.",
    sentenceZh: "只放图标、不放可见文字的按钮。",
    prompt:
      "Use an icon button with an aria-label that says what it does. The accessible name is the label, not the icon.",
    promptZh:
      "做图标按钮时用 aria-label 写明它做什么。读屏读到的是这句名字，不是图标本身。",
  },
  {
    slug: "link",
    group: "actions",
    name: "Link",
    nameZh: "链接",
    aliases: ["hyperlink", "anchor", "超链接"],
    sentence: "Text that takes a person to another place.",
    sentenceZh: "点了会去另一个地方的文字。",
    prompt:
      "Use a link to go to another page. Use a button when the press does something here.",
    promptZh: "去另一个页面用链接。在当前页面里做一件事用按钮。",
  },
  {
    slug: "text-field",
    group: "writing",
    name: "Text field",
    nameZh: "输入框",
    aliases: ["input", "text box", "单行输入"],
    sentence: "One line where a person types.",
    sentenceZh: "让人打一行字的地方。",
    prompt: "Install UI Lab input and use it for a single-line text field.",
    promptZh: "安装 UI Lab 的 input，用它做单行输入框。",
    component: {
      category: "motion",
      slug: "input",
      previewKey: "motion/input",
      installSlug: "input",
    },
  },
  {
    slug: "text-area",
    group: "writing",
    name: "Text area",
    nameZh: "多行输入",
    aliases: ["textarea", "多行文本框"],
    sentence: "A field for more than one line of text.",
    sentenceZh: "可以写下多行文字的输入区。",
    prompt:
      "Use a text area when the person may write several lines. Keep a single-line text field for a name or a search.",
    promptZh: "可能写好几行时用多行输入。名字和搜索仍用单行输入框。",
  },
  {
    slug: "search-field",
    group: "writing",
    name: "Search field",
    nameZh: "搜索框",
    aliases: ["search box", "search bar"],
    sentence: "A field meant for finding something.",
    sentenceZh: "用来找东西的输入框。",
    prompt:
      "Use a search field, with a search icon and a submit action, when the person is looking something up.",
    promptZh: "人要查找时用搜索框，带搜索图标和提交动作。",
  },
  {
    slug: "password-field",
    group: "writing",
    name: "Password field",
    nameZh: "密码框",
    aliases: ["masked input", "密码输入"],
    sentence: "A field that hides what is typed, with a way to reveal it.",
    sentenceZh: "把打出来的字盖住，并可以再显示出来。",
    prompt:
      "Use a password field that masks the characters and gives a control to show them.",
    promptZh: "密码框默认盖住字符，并提供一个控件把密码显示出来。",
  },
  {
    slug: "checkbox",
    group: "choice",
    name: "Checkbox",
    nameZh: "复选框",
    aliases: ["tick box", "check box", "勾选框"],
    sentence: "A box a person ticks. Several can be on at once.",
    sentenceZh: "可以勾上的小方框。好几个可以同时勾上。",
    prompt:
      "Install UI Lab checkbox. Use it when each choice is independent and more than one may be on.",
    promptZh: "安装 UI Lab 的 checkbox。每个选项各自成立、可以同时勾上好几个时用它。",
    component: {
      category: "motion",
      slug: "checkbox",
      previewKey: "motion/checkbox",
      installSlug: "checkbox",
    },
  },
  {
    slug: "radio",
    group: "choice",
    name: "Radio",
    nameZh: "单选",
    aliases: ["radio button", "radio group", "选项按钮"],
    sentence: "A set of choices where only one stays selected.",
    sentenceZh: "一组选项里只能留下一个。",
    prompt: "Install UI Lab radio. Use it when exactly one choice in the group may be selected.",
    promptZh: "安装 UI Lab 的 radio。这一组里只能选中一个时用它。",
    component: {
      category: "motion",
      slug: "radio",
      previewKey: "motion/radio",
      installSlug: "radio",
    },
  },
  {
    slug: "switch",
    group: "choice",
    name: "Switch",
    nameZh: "开关",
    aliases: ["toggle", "on/off switch"],
    sentence: "A control that turns one setting on or off.",
    sentenceZh: "把一项设置打开或关掉的控件。",
    prompt: "Install UI Lab switch. Use it for one setting that is either on or off.",
    promptZh: "安装 UI Lab 的 switch。一项设置只有开和关时用它。",
    component: {
      category: "motion",
      slug: "switch",
      previewKey: "motion/switch",
      installSlug: "switch",
    },
  },
  {
    slug: "select",
    group: "choice",
    name: "Select",
    nameZh: "下拉选择",
    aliases: ["dropdown", "picker", "选择器"],
    sentence: "A closed list. The person opens it and picks one. They do not type a new value.",
    sentenceZh: "收起的一张清单。打开后选一个，不能另打一个新值。",
    prompt:
      "Install UI Lab select when the person picks one value from a list and cannot type their own.",
    promptZh: "人要从清单里选一个、不能自己输入时，安装 UI Lab 的 select。",
    component: {
      category: "motion",
      slug: "select",
      previewKey: "motion/select",
      installSlug: "select",
    },
  },
  {
    slug: "combobox",
    group: "choice",
    name: "Combobox",
    nameZh: "组合框",
    aliases: ["autocomplete", "typeahead", "可输入下拉"],
    sentence: "A field where a person can type and also pick from suggestions.",
    sentenceZh: "既能打字，也能从建议里选的输入框。",
    prompt:
      "Use a combobox when the person may type and may also pick a suggestion. Use a select when they can only pick.",
    promptZh: "既能输入又能从建议里选，用组合框。只能从清单里选，用下拉选择。",
  },
  {
    slug: "slider",
    group: "choice",
    name: "Slider",
    nameZh: "滑块",
    aliases: ["range", "track and thumb"],
    sentence: "A thumb the person drags along a track to set a value.",
    sentenceZh: "沿轨道拖动滑块来设定一个值。",
    prompt: "Install UI Lab range-slider when the person sets a value by dragging.",
    promptZh: "靠拖动来设一个值时，安装 UI Lab 的 range-slider。",
    component: {
      category: "motion",
      slug: "range-slider",
      previewKey: "motion/range-slider",
      installSlug: "range-slider",
    },
  },
  {
    slug: "sidebar",
    group: "navigation",
    name: "Sidebar",
    nameZh: "侧边栏",
    aliases: ["side nav", "rail", "侧栏"],
    sentence: "A column beside the page that holds navigation or tools.",
    sentenceZh: "贴在页面一侧、放导航或工具的一栏。",
    prompt:
      "Use a sidebar for navigation that stays beside the page. A drawer covers the page and then goes away; a sidebar stays.",
    promptZh:
      "导航要一直留在页面旁边时用侧边栏。盖住页面、看完就走的是抽屉。",
  },
  {
    slug: "header",
    group: "navigation",
    name: "Header",
    nameZh: "顶栏",
    aliases: ["navbar", "top bar", "导航栏"],
    sentence: "The bar across the top of a page.",
    sentenceZh: "横在页面最上面的一条。",
    prompt: "Put the site name and the main links in a header across the top of the page.",
    promptZh: "把站点名字和主要链接放在页面顶部的顶栏里。",
  },
  {
    slug: "tabs",
    group: "navigation",
    name: "Tabs",
    nameZh: "选项卡",
    aliases: ["tab bar", "tabbed panels"],
    sentence: "A row of labels that switches which panel is visible.",
    sentenceZh: "一排标签，用来切换眼前的那一块内容。",
    prompt: "Install UI Lab tabs when one row of labels switches the panel underneath.",
    promptZh: "一排标签切换下面的内容时，安装 UI Lab 的 tabs。",
    component: {
      category: "motion",
      slug: "tabs",
      previewKey: "motion/tabs",
      installSlug: "tabs",
    },
  },
  {
    slug: "breadcrumb",
    group: "navigation",
    name: "Breadcrumb",
    nameZh: "面包屑",
    aliases: ["breadcrumb trail", "路径导航"],
    sentence: "The path from the top of the site down to this page.",
    sentenceZh: "从站点顶层走到当前这一页的路径。",
    prompt: "Show a breadcrumb of the parent pages when the person may need to step back up.",
    promptZh: "人可能要退回上层时，显示从站点顶层走到当前页的面包屑。",
  },
  {
    slug: "pagination",
    group: "navigation",
    name: "Pagination",
    nameZh: "分页",
    aliases: ["pager", "页码"],
    sentence: "Controls that move between pages of the same list.",
    sentenceZh: "在同一份清单的各页之间移动的控件。",
    prompt: "Use pagination when a list is split into numbered pages.",
    promptZh: "一份清单拆成带页码的几页时，用分页。",
  },
  {
    slug: "menu",
    group: "navigation",
    name: "Menu",
    nameZh: "菜单",
    aliases: ["command list", "命令列表"],
    sentence: "A list of commands or destinations a person can choose.",
    sentenceZh: "一组可以点的命令或目的地。",
    prompt:
      "Install UI Lab dropdown-menu for a menu of commands. The same component is the dropdown menu.",
    promptZh:
      "一组命令用 UI Lab 的 dropdown-menu。从按钮展开的那一种，也是这个组件。",
    component: {
      category: "motion",
      slug: "dropdown-menu",
      previewKey: "motion/dropdown-menu",
      installSlug: "dropdown-menu",
    },
  },
  {
    slug: "hamburger",
    group: "jargon",
    name: "Hamburger",
    nameZh: "汉堡菜单",
    aliases: ["three-line menu", "nav button", "三道杠"],
    sentence: "The three-line button that opens the navigation.",
    sentenceZh: "三道横线的按钮，点开才出现导航。",
    prompt:
      "Use a hamburger button to open navigation on a narrow screen. Give it an accessible name such as Menu.",
    promptZh: "窄屏用汉堡按钮打开导航。给它一个可读的名字，例如「菜单」。",
  },
  {
    slug: "kebab",
    group: "jargon",
    name: "Kebab",
    nameZh: "竖三点",
    aliases: ["overflow menu", "three-dot menu", "更多"],
    sentence: "A vertical three-dot button that opens less-used commands.",
    sentenceZh: "竖着的三个点，点开后是较少用的命令。",
    prompt:
      "Use a vertical three-dot kebab for commands that do not fit in the main row. Horizontal three dots are meatballs.",
    promptZh: "主操作排不下的命令，用竖着的三点。横着的三点是另一回事。",
  },
  {
    slug: "dialog",
    group: "overlay",
    name: "Dialog",
    nameZh: "对话框",
    aliases: ["modal", "弹窗", "popup"],
    sentence: "A panel that asks for attention and sits over the page.",
    sentenceZh: "浮在页面上、要人先处理的一块面板。",
    prompt:
      "Use a dialog when the person should deal with this panel before going back to the page. Keep the title and a way to close it.",
    promptZh: "要人先处理这块面板再回到页面时，用对话框。写上标题，并给一个关闭的办法。",
    related: {
      category: "motion",
      slug: "morphing-modal",
      name: "Morphing modal",
      nameZh: "变形弹窗",
    },
  },
  {
    slug: "drawer",
    group: "overlay",
    name: "Drawer",
    nameZh: "抽屉",
    aliases: ["sheet", "side sheet", "侧滑"],
    sentence: "A panel that slides in from the edge and covers part of the page.",
    sentenceZh: "从屏幕边缘滑入、盖住页面一部分的面板。",
    prompt:
      "Install UI Lab drawer when a panel slides in from the side and then leaves. A sidebar stays put.",
    promptZh: "面板从侧面滑入、然后再离开，安装 UI Lab 的 drawer。一直留在旁边的是侧边栏。",
    component: {
      category: "motion",
      slug: "drawer",
      previewKey: "motion/drawer",
      installSlug: "drawer",
    },
  },
  {
    slug: "popover",
    group: "overlay",
    name: "Popover",
    nameZh: "气泡",
    aliases: ["flyout", "popup panel", "浮层"],
    sentence: "A small panel anchored to the thing that opened it.",
    sentenceZh: "锚在打开它的那一块旁边的小面板。",
    prompt: "Install UI Lab popover for a panel anchored to its trigger.",
    promptZh: "小面板要锚在触发它的那一块旁边时，安装 UI Lab 的 popover。",
    component: {
      category: "motion",
      slug: "popover",
      previewKey: "motion/popover",
      installSlug: "popover",
    },
  },
  {
    slug: "tooltip",
    group: "overlay",
    name: "Tooltip",
    nameZh: "文字提示",
    aliases: ["hint", "hover tip"],
    sentence: "A short hint that appears on hover or focus.",
    sentenceZh: "悬停或聚焦时出现的一句短提示。",
    prompt: "Install UI Lab tooltip for a short hint on hover or keyboard focus.",
    promptZh: "悬停或键盘聚焦时给一句短提示，安装 UI Lab 的 tooltip。",
    component: {
      category: "motion",
      slug: "tooltip",
      previewKey: "motion/tooltip",
      installSlug: "tooltip",
    },
  },
  {
    slug: "dropdown-menu",
    group: "overlay",
    name: "Dropdown menu",
    nameZh: "下拉菜单",
    aliases: ["pulldown", "弹出菜单"],
    sentence: "A list of commands that opens from a button and closes after a choice.",
    sentenceZh: "从按钮展开的命令列表，选完就收起。",
    prompt: "Install UI Lab dropdown-menu when commands open from a button and close after one is chosen.",
    promptZh: "命令从按钮展开、选完就收起时，安装 UI Lab 的 dropdown-menu。",
    component: {
      category: "motion",
      slug: "dropdown-menu",
      previewKey: "motion/dropdown-menu",
      installSlug: "dropdown-menu",
    },
  },
  {
    slug: "toast",
    group: "overlay",
    name: "Toast",
    nameZh: "提示",
    aliases: ["snackbar", "消息条", "notification"],
    sentence: "A short message that appears, then leaves on its own.",
    sentenceZh: "短暂出现、然后自己走开的一句消息。",
    prompt: "Install UI Lab animated-toast-stack for a short message that appears and then leaves.",
    promptZh: "一句消息短暂出现再离开，安装 UI Lab 的 animated-toast-stack。",
    component: {
      category: "motion",
      slug: "animated-toast-stack",
      previewKey: "motion/animated-toast-stack",
      installSlug: "animated-toast-stack",
    },
  },
  {
    slug: "alert",
    group: "feedback",
    name: "Alert",
    nameZh: "警告",
    aliases: ["banner", "callout", "提示条"],
    sentence: "A message that stays on the page until the person handles it.",
    sentenceZh: "留在页面上、等人处理的一条消息。",
    prompt:
      "Use an alert for a message that stays in the page. Use a toast when the message should leave on its own.",
    promptZh: "消息要留在页面里用警告。消息自己走开用提示。",
  },
  {
    slug: "badge",
    group: "feedback",
    name: "Badge",
    nameZh: "徽标",
    aliases: ["count", "status dot", "角标"],
    sentence: "A small mark for a count or a status.",
    sentenceZh: "标个数或状态的一小块。",
    prompt: "Install UI Lab animated-badge for a small status or count mark.",
    promptZh: "用一小块标出状态或数量时，安装 UI Lab 的 animated-badge。",
    component: {
      category: "motion",
      slug: "animated-badge",
      previewKey: "motion/animated-badge",
      installSlug: "animated-badge",
    },
  },
  {
    slug: "progress",
    group: "feedback",
    name: "Progress",
    nameZh: "进度",
    aliases: ["progress bar", "进度条"],
    sentence: "A bar that shows how far a task has gone.",
    sentenceZh: "一条用来表示事情做到哪的条。",
    prompt:
      "Use a progress bar when you know how much of the task is done. Use a spinner when you only know that it is still working.",
    promptZh: "知道做到多少时用进度条。只知道还在进行时用加载。",
  },
  {
    slug: "spinner",
    group: "feedback",
    name: "Spinner",
    nameZh: "加载",
    aliases: ["loader", "throbber", "忙碌指示"],
    sentence: "A mark that something is still working, without saying how far.",
    sentenceZh: "表示还在进行，但不说出做到多少。",
    prompt: "Install UI Lab loader when work is in progress and the amount done is unknown.",
    promptZh: "还在进行、又不知道做到多少时，安装 UI Lab 的 loader。",
    component: {
      category: "motion",
      slug: "loader",
      previewKey: "motion/loader",
      installSlug: "loader",
    },
  },
  {
    slug: "skeleton",
    group: "feedback",
    name: "Skeleton",
    nameZh: "骨架屏",
    aliases: ["placeholder", "shimmer", "占位"],
    sentence: "Gray blocks in the shape of the content that is about to arrive.",
    sentenceZh: "用灰色块先占住即将出现的内容的形状。",
    prompt: "Install UI Lab skeleton while the real content is still loading.",
    promptZh: "真正的内容还在加载时，安装 UI Lab 的 skeleton 先占住形状。",
    component: {
      category: "motion",
      slug: "skeleton",
      previewKey: "motion/skeleton",
      installSlug: "skeleton",
    },
  },
  {
    slug: "empty-state",
    group: "feedback",
    name: "Empty state",
    nameZh: "空状态",
    aliases: ["blank slate", "zero state", "没有内容"],
    sentence: "What the page shows when there is nothing here yet.",
    sentenceZh: "这里还没有东西时，页面给出的说明。",
    prompt: "Install UI Lab empty-state-inbox when a list or page has nothing to show yet.",
    promptZh: "列表或页面还没有内容时，安装 UI Lab 的 empty-state-inbox。",
    component: {
      category: "blocks",
      slug: "empty-state",
      previewKey: "blocks/empty-state-inbox",
      installSlug: "empty-state-inbox",
    },
  },
  {
    slug: "card",
    group: "content",
    name: "Card",
    nameZh: "卡片",
    aliases: ["tile", "panel card"],
    sentence: "A bordered piece of content that can stand on its own.",
    sentenceZh: "自己能成立的一块带边界的内容。",
    prompt:
      "Group a title, a short text, and an action into a card. A tilt or a glare is an effect on a card, not the card itself.",
    promptZh: "把标题、短文和一次操作放进一张卡片。倾斜和眩光是加在卡片上的效果。",
  },
  {
    slug: "table",
    group: "content",
    name: "Table",
    nameZh: "表格",
    aliases: ["data grid", "数据表"],
    sentence: "Rows and columns of records.",
    sentenceZh: "用行和列排起来的记录。",
    prompt: "Install UI Lab table when the person is scanning records in rows and columns.",
    promptZh: "人要按行和列查看记录时，安装 UI Lab 的 table。",
    component: {
      category: "motion",
      slug: "table",
      previewKey: "motion/table",
      installSlug: "table",
    },
  },
  {
    slug: "avatar",
    group: "content",
    name: "Avatar",
    nameZh: "头像",
    aliases: ["profile picture", "用户头像"],
    sentence: "A picture or initials that stand for a person.",
    sentenceZh: "用图片或首字母代表一个人。",
    prompt: "Use an avatar for a person. Use initials when there is no picture.",
    promptZh: "代表一个人时用头像。没有图片就用姓名的首字母。",
  },
  {
    slug: "tag",
    group: "content",
    name: "Tag",
    nameZh: "标签",
    aliases: ["chip", "pill", "徽章"],
    sentence: "A small label that names a category.",
    sentenceZh: "标出一个分类的小块文字。",
    prompt: "Use a tag to name a category on a piece of content. A badge is for a count or a status.",
    promptZh: "给内容标一个分类用标签。标数量或状态用徽标。",
  },
  {
    slug: "accordion",
    group: "content",
    name: "Accordion",
    nameZh: "手风琴",
    aliases: ["disclosure", "collapsible", "折叠面板"],
    sentence: "A heading that opens and closes the text under it.",
    sentenceZh: "点标题，展开或收起下面的文字。",
    prompt: "Install UI Lab bouncy-accordion when a heading opens and closes the text under it.",
    promptZh: "点标题展开或收起下面的文字时，安装 UI Lab 的 bouncy-accordion。",
    component: {
      category: "motion",
      slug: "bouncy-accordion",
      previewKey: "motion/bouncy-accordion",
      installSlug: "bouncy-accordion",
    },
  },
  {
    slug: "list",
    group: "content",
    name: "List",
    nameZh: "列表",
    aliases: ["feed", "item rows", "清单"],
    sentence: "Items stacked in a single column.",
    sentenceZh: "在一列里叠起来的条目。",
    prompt: "Use a list when items stack in one column. Use a table when those items have columns to compare.",
    promptZh: "条目只是往下排，用列表。条目有好几列要对着看，用表格。",
  },
];

export function findConcept(slug: string) {
  return CONCEPTS.find((entry) => entry.slug === slug);
}
