import {
	type InspirationScreenshot,
	inspirationScreenshot,
} from "@/lib/inspiration-assets";
import type {
	InspirationAccess,
	InspirationCollectionKey,
	InspirationDomainKey,
	InspirationPageTypeKey,
	InspirationProvenance,
	InspirationRightsStatus,
	InspirationSiteBadgeKey,
	InspirationVisualTraitKey,
} from "@/lib/inspiration-taxonomy";

export type InspirationSite = {
	slug: string; entryKind: "site"; name: string; nameZh: string; aliases: readonly string[];
	url: string; canonicalUrl: string; description: string; descriptionZh: string; primaryTheme: "websites";
	domain: InspirationDomainKey; collections: readonly InspirationCollectionKey[]; pageTypes: readonly InspirationPageTypeKey[]; visualTraits: readonly InspirationVisualTraitKey[];
	badges: readonly InspirationSiteBadgeKey[]; previewColors: readonly string[]; relatedBrandSlug?: string;
	screenshot: InspirationScreenshot;
	access: InspirationAccess; accessNote?: string; accessNoteZh?: string; rightsStatus: InspirationRightsStatus;
	verdict: "accept"; confidence: "high" | "medium" | "low"; monitoringNote?: string; monitoringNoteZh?: string;
	provenance: readonly InspirationProvenance[]; reviewedAt: string;
};

const origin = (url: string): readonly InspirationProvenance[] => [{ url, kind: "first-party", note: "Reviewed on the first-party website.", noteZh: "已在该品牌或机构的第一方网站核验。" }];

const INSPIRATION_SITE_RECORDS: readonly Omit<InspirationSite, "screenshot">[] = [
	{ slug: "anthropic", entryKind: "site", name: "Anthropic", nameZh: "Anthropic", aliases: ["Claude"], url: "https://www.anthropic.com/", canonicalUrl: "https://www.anthropic.com/", description: "AI research company presenting Claude through calm, editorial product storytelling.", descriptionZh: "以克制的编辑式产品叙事呈现 Claude 的 AI 研究公司。", primaryTheme: "websites", collections: [], domain: "ai-llm", pageTypes: ["marketing-site"], visualTraits: ["minimal", "typographic", "editorial", "photography-led"], badges: ["industry-reference"], previewColors: ["#F7F6F2", "#171716", "#D97757", "#C9C3B7"], relatedBrandSlug: "claude", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.anthropic.com/"), reviewedAt: "2026-07-28" },
	{ slug: "mistral-ai", entryKind: "site", name: "Mistral AI", nameZh: "Mistral AI", aliases: ["Mistral"], url: "https://mistral.ai/", canonicalUrl: "https://mistral.ai/", description: "European AI platform framed with a high-contrast, technical and energetic identity.", descriptionZh: "以高对比、技术感和能量感呈现的欧洲 AI 平台。", primaryTheme: "websites", collections: [], domain: "ai-llm", pageTypes: ["marketing-site", "product-page"], visualTraits: ["bold", "typographic", "futuristic", "animated"], badges: ["industry-reference"], previewColors: ["#FFF8E8", "#121212", "#FF7000", "#FFCC00", "#6366F1"], relatedBrandSlug: "mistral.ai", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://mistral.ai/"), reviewedAt: "2026-07-28" },
	{ slug: "vercel", entryKind: "site", name: "Vercel", nameZh: "Vercel", aliases: ["Vercel platform"], url: "https://vercel.com/", canonicalUrl: "https://vercel.com/", description: "Developer platform whose sparse black-and-white shell lets product demos carry the argument.", descriptionZh: "以黑白极简外壳承托产品演示的开发者平台。", primaryTheme: "websites", collections: [], domain: "developer-tools", pageTypes: ["marketing-site", "product-page"], visualTraits: ["minimal", "monochrome", "typographic", "dark-mode"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#000000", "#EAEAEA", "#6B6B6B"], relatedBrandSlug: "vercel", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://vercel.com/"), reviewedAt: "2026-07-28" },
	{ slug: "cursor", entryKind: "site", name: "Cursor", nameZh: "Cursor", aliases: ["AI code editor"], url: "https://cursor.com/", canonicalUrl: "https://cursor.com/", description: "AI code editor landing page mixing dense product proof with luminous developer-tool imagery.", descriptionZh: "以密集产品证据和发光开发工具视觉组合的 AI 代码编辑器页面。", primaryTheme: "websites", collections: [], domain: "developer-tools", pageTypes: ["landing-page", "product-page"], visualTraits: ["dark-mode", "futuristic", "animated", "typographic"], badges: ["industry-reference"], previewColors: ["#111111", "#F4F4F0", "#7776FF", "#B6FF5C", "#2B2B2B"], relatedBrandSlug: "cursor", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://cursor.com/"), reviewedAt: "2026-07-28" },
	{ slug: "animejs", entryKind: "site", name: "Anime.js", nameZh: "Anime.js 动画引擎", aliases: ["Anime JS", "animejs", "JavaScript Animation Engine"], url: "https://animejs.com/", canonicalUrl: "https://animejs.com/", description: "JavaScript animation engine presented through a motion-led product page, interactive examples, documentation, and an easing editor.", descriptionZh: "通过动效主导的产品页、交互示例、文档与缓动编辑器呈现的 JavaScript 动画引擎官网。", primaryTheme: "websites", collections: [], domain: "developer-tools", pageTypes: ["marketing-site", "docs", "experimental"], visualTraits: ["dark-mode", "bold", "typographic", "animated"], badges: ["editor-pick"], previewColors: ["#111111", "#FFFFFF", "#F6D860", "#F05252", "#7C5CFC"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: [{ url: "https://animejs.com/", kind: "first-party", note: "Official product page for the JavaScript animation engine and its interactive capabilities.", noteZh: "JavaScript 动画引擎及其交互能力的官方产品页。" }, { url: "https://animejs.com/documentation/", kind: "first-party", note: "Official documentation covering animation, timeline, draggable, SVG, scroll, and easing APIs.", noteZh: "官方文档覆盖动画、时间线、拖拽、SVG、滚动与缓动 API。" }], reviewedAt: "2026-08-10" },
	{ slug: "supabase", entryKind: "site", name: "Supabase", nameZh: "Supabase", aliases: ["open source backend"], url: "https://supabase.com/", canonicalUrl: "https://supabase.com/", description: "Open-source backend platform using a confident green signal against code-oriented dark surfaces.", descriptionZh: "以鲜明绿色信号与代码化深色界面呈现的开源后端平台。", primaryTheme: "websites", collections: [], domain: "cloud-data-devops", pageTypes: ["marketing-site", "product-page", "docs"], visualTraits: ["dark-mode", "minimal", "futuristic", "typographic"], badges: ["industry-reference"], previewColors: ["#181818", "#FFFFFF", "#3ECF8E", "#1B1B1B", "#8B8B8B"], relatedBrandSlug: "supabase", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://supabase.com/"), reviewedAt: "2026-07-28" },
	{ slug: "sentry", entryKind: "site", name: "Sentry", nameZh: "Sentry", aliases: ["application monitoring"], url: "https://sentry.io/welcome/", canonicalUrl: "https://sentry.io/welcome/", description: "Application monitoring platform pairing expressive illustration with crisp dashboard-oriented structure.", descriptionZh: "以表现力插画和清晰仪表盘结构结合的应用监控平台。", primaryTheme: "websites", collections: [], domain: "cloud-data-devops", pageTypes: ["marketing-site", "product-page"], visualTraits: ["bold", "illustrative", "typographic", "animated"], badges: ["industry-reference"], previewColors: ["#362D59", "#FFFFFF", "#F26A5A", "#7554C0", "#F5F1FF"], relatedBrandSlug: "sentry", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://sentry.io/welcome/"), reviewedAt: "2026-07-28" },
	{ slug: "linear", entryKind: "site", name: "Linear", nameZh: "Linear", aliases: ["Linear.app"], url: "https://linear.app/", canonicalUrl: "https://linear.app/", description: "Product-development system presented with restraint, polished gradients, and focused motion.", descriptionZh: "以极度克制、精致渐变和聚焦动效呈现的产品开发系统。", primaryTheme: "websites", collections: [], domain: "productivity-saas", pageTypes: ["marketing-site", "product-page"], visualTraits: ["minimal", "dark-mode", "futuristic", "animated"], badges: ["industry-reference"], previewColors: ["#090909", "#FFFFFF", "#5E6AD2", "#2A2A2A", "#A7A7A7"], relatedBrandSlug: "linear.app", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://linear.app/"), reviewedAt: "2026-07-28" },
	{ slug: "notion", entryKind: "site", name: "Notion", nameZh: "Notion", aliases: ["workspace"], url: "https://www.notion.com/", canonicalUrl: "https://www.notion.com/", description: "Workspace platform built around paper-like surfaces, modular examples, and friendly clarity.", descriptionZh: "以纸张感界面、模块化范例和亲和清晰度构成的协作工作台。", primaryTheme: "websites", collections: [], domain: "productivity-saas", pageTypes: ["marketing-site", "product-page"], visualTraits: ["minimal", "monochrome", "typographic", "illustrative"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#191919", "#F7F7F5", "#D9D9D9", "#2383E2"], relatedBrandSlug: "notion", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.notion.com/"), reviewedAt: "2026-07-28" },
	{ slug: "figma", entryKind: "site", name: "Figma", nameZh: "Figma", aliases: ["collaborative design"], url: "https://www.figma.com/", canonicalUrl: "https://www.figma.com/", description: "Collaborative design platform with a bright, modular interface language and abundant product proof.", descriptionZh: "以明亮模块化界面语言和丰富产品实证呈现的协作设计平台。", primaryTheme: "websites", collections: [], domain: "design-creative", pageTypes: ["marketing-site", "product-page"], visualTraits: ["bold", "playful", "typographic", "animated"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#1E1E1E", "#F24E1E", "#A259FF", "#0ACF83"], relatedBrandSlug: "figma", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.figma.com/"), reviewedAt: "2026-07-28" },
	{ slug: "framer", entryKind: "site", name: "Framer", nameZh: "Framer", aliases: ["AI website builder"], url: "https://www.framer.com/", canonicalUrl: "https://www.framer.com/", description: "AI website builder that turns its own editable canvas and showcase sites into the hero narrative.", descriptionZh: "把可编辑画布和案例站点本身作为主叙事的 AI 建站工具。", primaryTheme: "websites", collections: [], domain: "design-creative", pageTypes: ["marketing-site", "product-page"], visualTraits: ["minimal", "typographic", "animated", "futuristic"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#111111", "#7B61FF", "#B5FF4A", "#EBEBEB"], relatedBrandSlug: "framer", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.framer.com/"), reviewedAt: "2026-07-28" },
	{ slug: "stripe", entryKind: "site", name: "Stripe", nameZh: "Stripe", aliases: ["financial infrastructure"], url: "https://stripe.com/", canonicalUrl: "https://stripe.com/", description: "Financial infrastructure story told through layered gradients, data proof, and editorial photography.", descriptionZh: "以层叠渐变、数据背书和编辑式摄影讲述金融基础设施。", primaryTheme: "websites", collections: [], domain: "fintech-crypto", pageTypes: ["marketing-site", "product-page"], visualTraits: ["bold", "futuristic", "animated", "photography-led"], badges: ["industry-reference"], previewColors: ["#635BFF", "#0A2540", "#FFFFFF", "#00D4FF", "#E8F7FF"], relatedBrandSlug: "stripe", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://stripe.com/"), reviewedAt: "2026-07-28" },
	{ slug: "wise", entryKind: "site", name: "Wise", nameZh: "Wise", aliases: ["cross-border money"], url: "https://wise.com/", canonicalUrl: "https://wise.com/", description: "Cross-border money service using direct language, practical calculators, and a distinctive green field.", descriptionZh: "以直白文案、实用汇率计算器和标志性绿色呈现的跨境资金服务。", primaryTheme: "websites", collections: [], domain: "fintech-crypto", pageTypes: ["marketing-site", "product-page"], visualTraits: ["bold", "typographic", "minimal"], badges: ["industry-reference"], previewColors: ["#163300", "#9FE870", "#FFFFFF", "#0E2F25", "#D8F7BE"], relatedBrandSlug: "wise", access: "public", accessNote: "Public; country-specific content detected (UK).", accessNoteZh: "公开访问；内容会随国家地区变化。", rightsStatus: "external-only", verdict: "accept", confidence: "high", monitoringNote: "Regional copy, rates, and product availability.", monitoringNoteZh: "关注地区文案、汇率与产品可用性。", provenance: origin("https://wise.com/"), reviewedAt: "2026-07-28" },
	{ slug: "aesop", entryKind: "site", name: "Aesop", nameZh: "伊索", aliases: ["Aēsop"], url: "https://www.aesop.com/", canonicalUrl: "https://www.aesop.com/", description: "Skincare commerce presented like a quiet design journal, with tactile product photography and warm restraint.", descriptionZh: "如安静设计期刊般呈现的护肤电商，强调触感产品摄影与暖调克制。", primaryTheme: "websites", collections: [], domain: "ecommerce-retail", pageTypes: ["ecommerce"], visualTraits: ["minimal", "editorial", "photography-led", "typographic"], badges: ["industry-reference"], previewColors: ["#F4F1E8", "#2B2924", "#A06E49", "#D9D0BE", "#FFFFFF"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.aesop.com/"), reviewedAt: "2026-07-28" },
	{ slug: "shopify", entryKind: "site", name: "Shopify", nameZh: "Shopify", aliases: ["commerce platform"], url: "https://www.shopify.com/", canonicalUrl: "https://www.shopify.com/", description: "Commerce platform landing page pairing big kinetic claims with merchant storefront evidence.", descriptionZh: "以大尺度动态宣言和商家店铺实例并置的电商平台落地页。", primaryTheme: "websites", collections: [], domain: "ecommerce-retail", pageTypes: ["marketing-site", "landing-page", "product-page"], visualTraits: ["bold", "typographic", "animated", "photography-led"], badges: ["industry-reference"], previewColors: ["#004C3F", "#95BF47", "#FFFFFF", "#F1FFF1", "#111111"], relatedBrandSlug: "shopify", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.shopify.com/"), reviewedAt: "2026-07-28" },
	{ slug: "the-verge", entryKind: "site", name: "The Verge", nameZh: "The Verge", aliases: ["Verge"], url: "https://www.theverge.com/", canonicalUrl: "https://www.theverge.com/", description: "Technology newsroom whose dense story grid is held by assertive type and neon-accented hierarchy.", descriptionZh: "以强势字体和霓虹强调层级组织密集内容网格的科技媒体。", primaryTheme: "websites", collections: [], domain: "media-content", pageTypes: ["editorial"], visualTraits: ["editorial", "bold", "typographic", "photography-led"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#000000", "#FF4DA0", "#00E5FF", "#E8E8E8"], relatedBrandSlug: "theverge", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.theverge.com/"), reviewedAt: "2026-07-28" },
	{ slug: "spotify", entryKind: "site", name: "Spotify", nameZh: "Spotify", aliases: ["music streaming"], url: "https://open.spotify.com/", canonicalUrl: "https://open.spotify.com/", description: "Streaming product entry focused on playback, discovery, and a dark interface punctuated by vivid green.", descriptionZh: "以播放、发现和鲜明绿色点亮深色界面的流媒体产品入口。", primaryTheme: "websites", collections: [], domain: "media-content", pageTypes: ["product-page"], visualTraits: ["dark-mode", "bold", "typographic", "animated"], badges: ["industry-reference"], previewColors: ["#191414", "#1DB954", "#FFFFFF", "#2A2A2A", "#B3B3B3"], relatedBrandSlug: "spotify", access: "public", accessNote: "The root website redirects to the player entry.", accessNoteZh: "官网入口会跳转至播放器页面。", rightsStatus: "external-only", verdict: "accept", confidence: "high", monitoringNote: "Regional catalogue and sign-in/player state.", monitoringNoteZh: "关注地区曲库与登录、播放器状态。", provenance: origin("https://open.spotify.com/"), reviewedAt: "2026-07-28" },
	{ slug: "apple", entryKind: "site", name: "Apple", nameZh: "Apple", aliases: ["Apple Store"], url: "https://www.apple.com/", canonicalUrl: "https://www.apple.com/", description: "Product storefront using generous whitespace, cinematic device photography, and controlled hierarchy.", descriptionZh: "以充裕留白、电影感设备摄影和严密层级呈现的消费科技产品站。", primaryTheme: "websites", collections: [], domain: "consumer-tech", pageTypes: ["marketing-site", "ecommerce", "product-page"], visualTraits: ["minimal", "photography-led", "typographic", "animated"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#1D1D1F", "#F5F5F7", "#0071E3", "#86868B"], relatedBrandSlug: "apple", access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.apple.com/"), reviewedAt: "2026-07-28" },
	{ slug: "nothing", entryKind: "site", name: "Nothing", nameZh: "Nothing", aliases: ["Nothing Tech"], url: "https://nothing.tech/", canonicalUrl: "https://nothing.tech/", description: "Consumer-tech brand using stark monochrome layouts, dot-matrix voice, and transparent-hardware imagery.", descriptionZh: "以强黑白排版、点阵语气和透明硬件影像呈现的消费科技品牌。", primaryTheme: "websites", collections: [], domain: "consumer-tech", pageTypes: ["marketing-site", "product-page", "ecommerce"], visualTraits: ["monochrome", "bold", "futuristic", "typographic"], badges: ["industry-reference"], previewColors: ["#000000", "#FFFFFF", "#FF3B30", "#D8D8D8", "#222222"], access: "public", accessNote: "Public; verifier was served a UK locale.", accessNoteZh: "公开访问；核验时被分配到英国地区版本。", rightsStatus: "external-only", verdict: "accept", confidence: "high", monitoringNote: "Locale-dependent offers and catalogue.", monitoringNoteZh: "关注随地区变化的优惠和商品目录。", provenance: origin("https://nothing.tech/"), reviewedAt: "2026-07-28" },
	{ slug: "polestar", entryKind: "site", name: "Polestar", nameZh: "极星", aliases: ["electric vehicle"], url: "https://www.polestar.com/us/", canonicalUrl: "https://www.polestar.com/us/", description: "Electric-car retail site treating vehicle photography, quiet type, and configuration paths as one system.", descriptionZh: "将车辆摄影、安静字体和配置路径整合为一体的电动车零售站。", primaryTheme: "websites", collections: [], domain: "automotive-mobility", pageTypes: ["marketing-site", "product-page", "ecommerce"], visualTraits: ["minimal", "photography-led", "typographic", "futuristic"], badges: ["industry-reference"], previewColors: ["#F6F6F4", "#101010", "#FFFFFF", "#777777", "#C9C9C5"], access: "public", accessNote: "Root redirects to a regional locale.", accessNoteZh: "根域会跳转到地区版本。", rightsStatus: "external-only", verdict: "accept", confidence: "high", monitoringNote: "Country selector changes vehicles, offers, and URL.", monitoringNoteZh: "关注国家选择器对车型、优惠与网址的影响。", provenance: origin("https://www.polestar.com/us/"), reviewedAt: "2026-07-28" },
	{ slug: "aman", entryKind: "site", name: "Aman", nameZh: "安缦", aliases: ["Aman Resorts"], url: "https://www.aman.com/", canonicalUrl: "https://www.aman.com/", description: "Luxury hospitality site paced like a destination journal, with expansive nature imagery and hushed serif-led layouts.", descriptionZh: "如目的地期刊般节奏舒缓的奢华酒店站，以自然大图和低声量衬线排版为主。", primaryTheme: "websites", collections: [], domain: "travel-hospitality", pageTypes: ["marketing-site", "ecommerce"], visualTraits: ["minimal", "editorial", "photography-led", "typographic"], badges: ["industry-reference"], previewColors: ["#E8E2D6", "#1A1A18", "#80735D", "#FFFFFF", "#B5A38C"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.aman.com/"), reviewedAt: "2026-07-28" },
	{ slug: "duolingo", entryKind: "site", name: "Duolingo", nameZh: "多邻国", aliases: ["language learning"], url: "https://www.duolingo.com/", canonicalUrl: "https://www.duolingo.com/", description: "Language-learning product that makes progress feel like a cheerful game through mascot-led color and feedback.", descriptionZh: "以吉祥物色彩和即时反馈让语言学习呈现为轻快游戏的产品站。", primaryTheme: "websites", collections: [], domain: "education-knowledge", pageTypes: ["landing-page", "product-page"], visualTraits: ["playful", "bold", "illustrative", "animated"], badges: ["industry-reference"], previewColors: ["#58CC02", "#FFFFFF", "#1CB0F6", "#FFC800", "#CE82FF"], access: "public", accessNote: "Public, but the homepage returned minimal server-rendered text in verification.", accessNoteZh: "公开访问；核验时首页仅返回少量服务端渲染文本。", rightsStatus: "external-only", verdict: "accept", confidence: "medium", monitoringNote: "Client-rendered campaign changes.", monitoringNoteZh: "关注客户端渲染的活动页面变化。", provenance: origin("https://www.duolingo.com/"), reviewedAt: "2026-07-28" },
	{ slug: "headspace", entryKind: "site", name: "Headspace", nameZh: "Headspace", aliases: ["mental health"], url: "https://www.headspace.com/", canonicalUrl: "https://www.headspace.com/", description: "Mental-health subscription page built from soft color blocks, reassuring copy, and approachable illustration.", descriptionZh: "以柔和色块、安抚文案和亲和插画构成的心理健康订阅页面。", primaryTheme: "websites", collections: [], domain: "health-wellness", pageTypes: ["landing-page", "product-page"], visualTraits: ["playful", "illustrative", "bold", "typographic"], badges: ["industry-reference"], previewColors: ["#F47D31", "#6CB6FF", "#F6EADF", "#3B2D5A", "#FFFFFF"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.headspace.com/"), reviewedAt: "2026-07-28" },
	{ slug: "ssense", entryKind: "site", name: "SSENSE", nameZh: "SSENSE", aliases: ["fashion commerce"], url: "https://www.ssense.com/", canonicalUrl: "https://www.ssense.com/", description: "Luxury-fashion commerce driven by severe typography, editorial image crops, and a magazine-like product grid.", descriptionZh: "以冷峻字体、编辑式图片裁切和杂志感商品网格驱动的奢侈时尚电商。", primaryTheme: "websites", collections: [], domain: "fashion-luxury", pageTypes: ["ecommerce", "editorial"], visualTraits: ["minimal", "monochrome", "editorial", "photography-led"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#000000", "#F3F3F3", "#8A8A8A"], access: "public", accessNote: "Public; merchandising is market-dependent.", accessNoteZh: "公开访问；商品陈列会随市场地区变化。", rightsStatus: "external-only", verdict: "accept", confidence: "medium", monitoringNote: "Country, currency, and catalogue personalization.", monitoringNoteZh: "关注国家、货币与商品目录个性化。", provenance: origin("https://www.ssense.com/"), reviewedAt: "2026-07-28" },
	{ slug: "active-theory", entryKind: "site", name: "Active Theory", nameZh: "Active Theory", aliases: ["creative studio"], url: "https://activetheory.net/", canonicalUrl: "https://activetheory.net/", description: "Creative studio portfolio built as an immersive, motion-first digital experience rather than a conventional brochure.", descriptionZh: "以沉浸式、动效优先的数字体验而非传统画册方式呈现的创意工作室作品集。", primaryTheme: "websites", collections: [], domain: "agency-portfolio", pageTypes: ["portfolio", "experimental"], visualTraits: ["dark-mode", "animated", "three-dimensional", "futuristic"], badges: ["editor-pick"], previewColors: ["#080808", "#FFFFFF", "#5646FF", "#FF5C35", "#252525"], access: "public", accessNote: "Public; homepage is heavily client-rendered.", accessNoteZh: "公开访问；首页高度依赖客户端渲染。", rightsStatus: "external-only", verdict: "accept", confidence: "medium", monitoringNote: "WebGL/client rendering and performance or accessibility fallback.", monitoringNoteZh: "关注 WebGL、客户端渲染与性能、无障碍降级。", provenance: origin("https://activetheory.net/"), reviewedAt: "2026-07-28" },
	{ slug: "oatly", entryKind: "site", name: "Oatly", nameZh: "Oatly", aliases: ["oat drink"], url: "https://www.oatly.com/", canonicalUrl: "https://www.oatly.com/", description: "Oat-drink brand site whose loud, handwritten editorial attitude turns product browsing into a campaign surface.", descriptionZh: "以高声量手写编辑语气把燕麦饮品浏览转化为品牌传播场的食品站。", primaryTheme: "websites", collections: [], domain: "food-beverage", pageTypes: ["marketing-site", "ecommerce", "editorial"], visualTraits: ["bold", "playful", "typographic", "illustrative"], badges: ["industry-reference"], previewColors: ["#000000", "#FFFFFF", "#D7E7A9", "#F5E6D3", "#FF6B35"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.oatly.com/"), reviewedAt: "2026-07-28" },
	{ slug: "moma", entryKind: "site", name: "MoMA", nameZh: "纽约现代艺术博物馆", aliases: ["Museum of Modern Art"], url: "https://www.moma.org/", canonicalUrl: "https://www.moma.org/", description: "Museum homepage using a disciplined black-and-white system to let exhibitions and collection imagery set the rhythm.", descriptionZh: "以严谨黑白系统让展览与馆藏图像主导节奏的博物馆首页。", primaryTheme: "websites", collections: [], domain: "culture-nonprofit", pageTypes: ["editorial", "ecommerce"], visualTraits: ["minimal", "editorial", "monochrome", "photography-led"], badges: ["industry-reference"], previewColors: ["#FFFFFF", "#000000", "#E6E6E6", "#D71920", "#777777"], access: "public", rightsStatus: "external-only", verdict: "accept", confidence: "high", provenance: origin("https://www.moma.org/"), reviewedAt: "2026-07-28" },
];

export const INSPIRATION_SITES: readonly InspirationSite[] =
	INSPIRATION_SITE_RECORDS.map((site) => ({
		...site,
		screenshot: inspirationScreenshot("sites", site.slug, site.url),
	}));
